<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class ActionServiceCondition
{
    /** @example null */
    #[SerializedName('event')]
    public ?\Zitadel\Client\Models\ActionServiceEventExecution $event = null;

    /** @example null */
    #[SerializedName('function')]
    public ?\Zitadel\Client\Models\ActionServiceFunctionExecution $function_ = null;

    /** @example null */
    #[SerializedName('request')]
    public ?\Zitadel\Client\Models\ActionServiceRequestExecution $request = null;

    /** @example null */
    #[SerializedName('response')]
    public ?\Zitadel\Client\Models\ActionServiceResponseExecution $response = null;

    /**
     */
    public function __construct(
        ?\Zitadel\Client\Models\ActionServiceEventExecution $event = null,
        ?\Zitadel\Client\Models\ActionServiceFunctionExecution $function_ = null,
        ?\Zitadel\Client\Models\ActionServiceRequestExecution $request = null,
        ?\Zitadel\Client\Models\ActionServiceResponseExecution $response = null,
    ) {
        $this->event = $event;
        $this->function_ = $function_;
        $this->request = $request;
        $this->response = $response;
    }
}
