<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class ActionServiceEventExecution
{
    /**
     * Define all events as condition.  After any event is created, the execution is triggered.
     * @example null
     */
    #[SerializedName('all')]
    public ?bool $all = null;

    /**
     * Define a specific event as condition.  After this event is created, the execution is triggered.
     * @example null
     */
    #[SerializedName('event')]
    public ?string $event = null;

    /**
     * Define an event group as condition.  After any event under this group is created, the execution is triggered.
     * @example null
     */
    #[SerializedName('group')]
    public ?string $group = null;

    /**
     */
    public function __construct(
        ?bool $all = null,
        ?string $event = null,
        ?string $group = null,
    ) {
        $this->all = $all;
        $this->event = $event;
        $this->group = $group;
    }
}
