<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

/* phpcs:ignoreFile */

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class ApplicationServiceApplicationSearchFilter
{
    /** @example null */
    #[SerializedName('clientIdFilter')]
    public ?\Zitadel\Client\Models\ApplicationServiceClientIDFilter $clientIdFilter = null;

    /** @example null */
    #[SerializedName('entityIdFilter')]
    public ?\Zitadel\Client\Models\ApplicationServiceEntityIDFilter $entityIdFilter = null;

    /** @example null */
    #[SerializedName('nameFilter')]
    public ?\Zitadel\Client\Models\ApplicationServiceApplicationNameFilter $nameFilter = null;

    /** @example null */
    #[SerializedName('projectIdFilter')]
    public ?\Zitadel\Client\Models\ApplicationServiceProjectIDFilter $projectIdFilter = null;

    /** @example null */
    #[SerializedName('stateFilter')]
    public ?\Zitadel\Client\Models\ApplicationServiceApplicationState $stateFilter = null;

    /** @example null */
    #[SerializedName('typeFilter')]
    public ?\Zitadel\Client\Models\ApplicationServiceApplicationType $typeFilter = null;

    /**
     */
    public function __construct(
        ?\Zitadel\Client\Models\ApplicationServiceClientIDFilter $clientIdFilter = null,
        ?\Zitadel\Client\Models\ApplicationServiceEntityIDFilter $entityIdFilter = null,
        ?\Zitadel\Client\Models\ApplicationServiceApplicationNameFilter $nameFilter = null,
        ?\Zitadel\Client\Models\ApplicationServiceProjectIDFilter $projectIdFilter = null,
        ?\Zitadel\Client\Models\ApplicationServiceApplicationState $stateFilter = null,
        ?\Zitadel\Client\Models\ApplicationServiceApplicationType $typeFilter = null,
    ) {
        $this->clientIdFilter = $clientIdFilter;
        $this->entityIdFilter = $entityIdFilter;
        $this->nameFilter = $nameFilter;
        $this->projectIdFilter = $projectIdFilter;
        $this->stateFilter = $stateFilter;
        $this->typeFilter = $typeFilter;
    }
}
