<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class ApplicationServiceCreateOIDCApplicationResponse
{
    /**
     * The unique OAuth2/OIDC client_id used for authentication of the application,  e.g. at the token endpoint.
     * @example null
     */
    #[SerializedName('clientId')]
    public ?string $clientId = null;

    /**
     * In case of using the OIDCAuthMethodType.OIDC_AUTH_METHOD_TYPE_CLIENT_SECRET_BASIC  or OIDCAuthMethodType.OIDC_AUTH_METHOD_TYPE_CLIENT_SECRET_POST the client_secret is generated and returned.  It must be stored safely, as it will not be possible to retrieve it again.  A new client_secret can be generated using the GenerateClientSecret endpoint.
     * @example null
     */
    #[SerializedName('clientSecret')]
    public ?string $clientSecret = null;

    /**
     * NonCompliant specifies whether the config is OIDC compliant. A production configuration SHOULD be compliant.  Non-compliant configurations can run into interoperability issues with OIDC libraries and tools.  Compliance problems are listed in the compliance_problems field.
     * @example null
     */
    #[SerializedName('nonCompliant')]
    public ?bool $nonCompliant = null;

    /**
     * ComplianceProblems lists the problems for non-compliant configurations.  In case of a compliant configuration, this list is empty.
     * @var \Ds\Vector<\Zitadel\Client\Models\ApplicationServiceOIDCLocalizedMessage>|null
     * @example null
     */
    #[SerializedName('complianceProblems')]
    public ?\Ds\Vector $complianceProblems = null;

    /**
     * @param \Ds\Vector<\Zitadel\Client\Models\ApplicationServiceOIDCLocalizedMessage>|null $complianceProblems
     */
    public function __construct(
        ?string $clientId = null,
        ?string $clientSecret = null,
        ?bool $nonCompliant = null,
        ?\Ds\Vector $complianceProblems = null,
    ) {
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->nonCompliant = $nonCompliant;
        $this->complianceProblems = $complianceProblems;
    }
}
