<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class BetaAuthorizationServiceCreateAuthorizationRequest
{
    /**
     * UserID is the ID of the user who should be granted the authorization.
     * @example null
     */
    #[SerializedName('userId')]
    public ?string $userId = null;

    /**
     * Project ID is the ID of the project the user should be authorized for.
     * @example null
     */
    #[SerializedName('projectId')]
    public ?string $projectId = null;

    /**
     * OrganizationID is the ID of the organization on which the authorization should be created.  The organization must either own the project or have a grant for the project.  If omitted, the authorization is created on the projects organization.
     * @example null
     */
    #[SerializedName('organizationId')]
    public ?string $organizationId = null;

    /**
     * RoleKeys are the keys of the roles the user should be granted.
     * @var \Ds\Vector<string>|null
     * @example null
     */
    #[SerializedName('roleKeys')]
    public ?\Ds\Vector $roleKeys = null;

    /**
     * @param \Ds\Vector<string>|null $roleKeys
     */
    public function __construct(
        ?string $userId = null,
        ?string $projectId = null,
        ?string $organizationId = null,
        ?\Ds\Vector $roleKeys = null,
    ) {
        $this->userId = $userId;
        $this->projectId = $projectId;
        $this->organizationId = $organizationId;
        $this->roleKeys = $roleKeys;
    }
}
