<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class BetaUserServiceSearchQuery
{
    /** @example null */
    #[SerializedName('andQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceAndQuery $andQuery = null;

    /** @example null */
    #[SerializedName('displayNameQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceDisplayNameQuery $displayNameQuery = null;

    /** @example null */
    #[SerializedName('emailQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceEmailQuery $emailQuery = null;

    /** @example null */
    #[SerializedName('firstNameQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceFirstNameQuery $firstNameQuery = null;

    /** @example null */
    #[SerializedName('inUserEmailsQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceInUserEmailsQuery $inUserEmailsQuery = null;

    /** @example null */
    #[SerializedName('inUserIdsQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceInUserIDQuery $inUserIdsQuery = null;

    /** @example null */
    #[SerializedName('lastNameQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceLastNameQuery $lastNameQuery = null;

    /** @example null */
    #[SerializedName('loginNameQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceLoginNameQuery $loginNameQuery = null;

    /** @example null */
    #[SerializedName('nickNameQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceNickNameQuery $nickNameQuery = null;

    /** @example null */
    #[SerializedName('notQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceNotQuery $notQuery = null;

    /** @example null */
    #[SerializedName('orQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceOrQuery $orQuery = null;

    /** @example null */
    #[SerializedName('organizationIdQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceOrganizationIdQuery $organizationIdQuery = null;

    /** @example null */
    #[SerializedName('phoneQuery')]
    public ?\Zitadel\Client\Models\BetaUserServicePhoneQuery $phoneQuery = null;

    /** @example null */
    #[SerializedName('stateQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceStateQuery $stateQuery = null;

    /** @example null */
    #[SerializedName('typeQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceTypeQuery $typeQuery = null;

    /** @example null */
    #[SerializedName('userNameQuery')]
    public ?\Zitadel\Client\Models\BetaUserServiceUserNameQuery $userNameQuery = null;

    /**
     */
    public function __construct(
        ?\Zitadel\Client\Models\BetaUserServiceAndQuery $andQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceDisplayNameQuery $displayNameQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceEmailQuery $emailQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceFirstNameQuery $firstNameQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceInUserEmailsQuery $inUserEmailsQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceInUserIDQuery $inUserIdsQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceLastNameQuery $lastNameQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceLoginNameQuery $loginNameQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceNickNameQuery $nickNameQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceNotQuery $notQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceOrQuery $orQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceOrganizationIdQuery $organizationIdQuery = null,
        ?\Zitadel\Client\Models\BetaUserServicePhoneQuery $phoneQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceStateQuery $stateQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceTypeQuery $typeQuery = null,
        ?\Zitadel\Client\Models\BetaUserServiceUserNameQuery $userNameQuery = null,
    ) {
        $this->andQuery = $andQuery;
        $this->displayNameQuery = $displayNameQuery;
        $this->emailQuery = $emailQuery;
        $this->firstNameQuery = $firstNameQuery;
        $this->inUserEmailsQuery = $inUserEmailsQuery;
        $this->inUserIdsQuery = $inUserIdsQuery;
        $this->lastNameQuery = $lastNameQuery;
        $this->loginNameQuery = $loginNameQuery;
        $this->nickNameQuery = $nickNameQuery;
        $this->notQuery = $notQuery;
        $this->orQuery = $orQuery;
        $this->organizationIdQuery = $organizationIdQuery;
        $this->phoneQuery = $phoneQuery;
        $this->stateQuery = $stateQuery;
        $this->typeQuery = $typeQuery;
        $this->userNameQuery = $userNameQuery;
    }
}
