<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

enum BetaInternalPermissionServiceAdministratorFieldName: string
{
    case ADMINISTRATOR_FIELD_NAME_UNSPECIFIED = 'ADMINISTRATOR_FIELD_NAME_UNSPECIFIED';
    case ADMINISTRATOR_FIELD_NAME_USER_ID = 'ADMINISTRATOR_FIELD_NAME_USER_ID';
    case ADMINISTRATOR_FIELD_NAME_CREATION_DATE = 'ADMINISTRATOR_FIELD_NAME_CREATION_DATE';
    case ADMINISTRATOR_FIELD_NAME_CHANGE_DATE = 'ADMINISTRATOR_FIELD_NAME_CHANGE_DATE';
}
