<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

/* phpcs:ignoreFile */

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class BetaSettingsServiceIdentityProvider
{
    #[SerializedName('id')]
    public ?string $id = null;

    #[SerializedName('name')]
    public ?string $name = null;

    #[SerializedName('type')]
    public ?\Zitadel\Client\Models\BetaSettingsServiceIdentityProviderType $type = null;

    /**
     */
    public function __construct(
        ?string $id = null,
        ?string $name = null,
        ?\Zitadel\Client\Models\BetaSettingsServiceIdentityProviderType $type = null,
    ) {
        $this->id = $id;
        $this->name = $name;
        $this->type = $type;
    }
}
