<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class BetaAuthorizationServiceUpdateAuthorizationRequest
{
    /**
     * ID is the unique identifier of the authorization.
     * @example null
     */
    #[SerializedName('id')]
    public ?string $id = null;

    /**
     * RoleKeys are the keys of the roles the user should be granted.  Note that any role keys previously granted to the user and not present in the list will be revoked.
     * @var \Ds\Vector<string>|null
     * @example null
     */
    #[SerializedName('roleKeys')]
    public ?\Ds\Vector $roleKeys = null;

    /**
     * @param \Ds\Vector<string>|null $roleKeys
     */
    public function __construct(
        ?string $id = null,
        ?\Ds\Vector $roleKeys = null,
    ) {
        $this->id = $id;
        $this->roleKeys = $roleKeys;
    }
}
