<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class BetaTelemetryServiceReportBaseInformationResponse
{
    /**
     * The report ID is a unique identifier for the report.  It is used to identify the report to be able to link it to the resource counts or other reports.  Note that the report ID is only valid for the same system ID.
     * @example null
     */
    #[SerializedName('reportId')]
    public ?string $reportId = null;

    /**
     */
    public function __construct(
        ?string $reportId = null,
    ) {
        $this->reportId = $reportId;
    }
}
