<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class IdentityProviderServiceAppleConfig
{
    /**
     * Client id (App ID or Service ID) provided by Apple.
     * @example null
     */
    #[SerializedName('clientId')]
    public ?string $clientId = null;

    /**
     * Team ID provided by Apple.
     * @example null
     */
    #[SerializedName('teamId')]
    public ?string $teamId = null;

    /**
     * ID of the private key generated by Apple.
     * @example null
     */
    #[SerializedName('keyId')]
    public ?string $keyId = null;

    /**
     * The scopes requested by ZITADEL during the request to Apple.
     * @var \Ds\Vector<string>|null
     * @example null
     */
    #[SerializedName('scopes')]
    public ?\Ds\Vector $scopes = null;

    /**
     * @param \Ds\Vector<string>|null $scopes
     */
    public function __construct(
        ?string $clientId = null,
        ?string $teamId = null,
        ?string $keyId = null,
        ?\Ds\Vector $scopes = null,
    ) {
        $this->clientId = $clientId;
        $this->teamId = $teamId;
        $this->keyId = $keyId;
        $this->scopes = $scopes;
    }
}
