<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

/* phpcs:ignoreFile */

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class InternalPermissionServiceUserPreferredLoginNameFilter
{
    /**
     * Search for administrators by the preferred login name of the user.
     * @example null
     */
    #[SerializedName('preferredLoginName')]
    public ?string $preferredLoginName = null;

    /** @example null */
    #[SerializedName('method')]
    public ?\Zitadel\Client\Models\InternalPermissionServiceTextFilterMethod $method = null;

    /**
     */
    public function __construct(
        ?string $preferredLoginName = null,
        ?\Zitadel\Client\Models\InternalPermissionServiceTextFilterMethod $method = null,
    ) {
        $this->preferredLoginName = $preferredLoginName;
        $this->method = $method;
    }
}
