<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

/* phpcs:ignoreFile */

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class OrganizationServiceListOrganizationsRequest
{
    /** @example null */
    #[SerializedName('query')]
    public ?\Zitadel\Client\Models\OrganizationServiceListQuery $query = null;

    /** @example null */
    #[SerializedName('sortingColumn')]
    public ?\Zitadel\Client\Models\OrganizationServiceOrganizationFieldName $sortingColumn = null;

    /**
     * criteria the client is looking for
     * @var \Ds\Vector<\Zitadel\Client\Models\OrganizationServiceSearchQuery>|null
     * @example null
     */
    #[SerializedName('queries')]
    public ?\Ds\Vector $queries = null;

    /**
     * @param \Ds\Vector<\Zitadel\Client\Models\OrganizationServiceSearchQuery>|null $queries
     */
    public function __construct(
        ?\Zitadel\Client\Models\OrganizationServiceListQuery $query = null,
        ?\Zitadel\Client\Models\OrganizationServiceOrganizationFieldName $sortingColumn = null,
        ?\Ds\Vector $queries = null,
    ) {
        $this->query = $query;
        $this->sortingColumn = $sortingColumn;
        $this->queries = $queries;
    }
}
