<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class ProjectServiceUpdateProjectRoleRequest
{
    /**
     * ProjectID is the unique identifier of the project.
     * @example null
     */
    #[SerializedName('projectId')]
    public ?string $projectId = null;

    /**
     * RoleKey identifies the role. It's the only relevant attribute for ZITADEL and  will be used for authorization checks and as claim in tokens and user info responses.  It cannot be changed. If you need a different key, remove the role and create a new one.
     * @example null
     */
    #[SerializedName('roleKey')]
    public ?string $roleKey = null;

    /**
     * DisplayName is the human readable name for the role, which might be displayed to users.  If omitted, the name will remain unchanged.
     * @example null
     */
    #[SerializedName('displayName')]
    public ?string $displayName = null;

    /**
     * Group allows grouping roles for display purposes. Zitadel will not handle it in any way.  It can be used to group roles in a UI to allow easier management for administrators.  If omitted, the group will remain unchanged.  This attribute is not to be confused with groups as a collection of users.
     * @example null
     */
    #[SerializedName('group')]
    public ?string $group = null;

    /**
     */
    public function __construct(
        ?string $projectId = null,
        ?string $roleKey = null,
        ?string $displayName = null,
        ?string $group = null,
    ) {
        $this->projectId = $projectId;
        $this->roleKey = $roleKey;
        $this->displayName = $displayName;
        $this->group = $group;
    }
}
