<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class ProjectServiceUpdateProjectGrantRequest
{
    /**
     * ProjectID is the unique identifier of the project.
     * @example null
     */
    #[SerializedName('projectId')]
    public ?string $projectId = null;

    /**
     * GrantedOrganizationID is the unique identifier of the organization the project was granted to.
     * @example null
     */
    #[SerializedName('grantedOrganizationId')]
    public ?string $grantedOrganizationId = null;

    /**
     * RoleKeys is a list of roles to be granted to the organization for self management.  The roles are identified by their keys.  Any roles not included in this list will be removed from the project grant.  If you want to add a role, make sure to include all other existing roles as well.  If any previous role is removed, all user grants for this project grant with this role will be removed as well.
     * @var \Ds\Vector<string>|null
     * @example null
     */
    #[SerializedName('roleKeys')]
    public ?\Ds\Vector $roleKeys = null;

    /**
     * @param \Ds\Vector<string>|null $roleKeys
     */
    public function __construct(
        ?string $projectId = null,
        ?string $grantedOrganizationId = null,
        ?\Ds\Vector $roleKeys = null,
    ) {
        $this->projectId = $projectId;
        $this->grantedOrganizationId = $grantedOrganizationId;
        $this->roleKeys = $roleKeys;
    }
}
