<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class SessionServiceUserAgentQuery
{
    /**
     * Finger print id of the user agent used for the session.  Set an empty fingerprint_id to use the user agent from the call.  If the user agent is not available from the current token, an error will be returned.
     * @example null
     */
    #[SerializedName('fingerprintId')]
    public ?string $fingerprintId = null;

    /**
     */
    public function __construct(
        ?string $fingerprintId = null,
    ) {
        $this->fingerprintId = $fingerprintId;
    }
}
