<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class SettingsServiceGetLockoutSettingsResponse
{
    /** @example null */
    #[SerializedName('details')]
    public ?\Zitadel\Client\Models\SettingsServiceDetails $details = null;

    /** @example null */
    #[SerializedName('settings')]
    public ?\Zitadel\Client\Models\SettingsServiceLockoutSettings $settings = null;

    /**
     */
    public function __construct(
        ?\Zitadel\Client\Models\SettingsServiceDetails $details = null,
        ?\Zitadel\Client\Models\SettingsServiceLockoutSettings $settings = null,
    ) {
        $this->details = $details;
        $this->settings = $settings;
    }
}
