<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class SettingsServiceSetHostedLoginTranslationRequest
{
    /**
     * The locale of the translations to be set.  Needs to be a BCP 47 language tag (e.g. \"en\", \"de\", \"fr-CH\").
     * @example null
     */
    #[SerializedName('locale')]
    public ?string $locale = null;

    /**
     * `Struct` represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, `Struct`  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for `Struct` is JSON object.
     * @var \Ds\Map<string, mixed>|null
     * @example null
     */
    #[SerializedName('translations')]
    public ?\Ds\Map $translations = null;

    /** @example null */
    #[SerializedName('instance')]
    public ?bool $instance = null;

    /** @example null */
    #[SerializedName('organizationId')]
    public ?string $organizationId = null;

    /**
     * @param \Ds\Map<string, mixed>|null $translations
     */
    public function __construct(
        ?string $locale = null,
        ?\Ds\Map $translations = null,
        ?bool $instance = null,
        ?string $organizationId = null,
    ) {
        $this->locale = $locale;
        $this->translations = $translations;
        $this->instance = $instance;
        $this->organizationId = $organizationId;
    }
}
