<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

/* phpcs:ignoreFile */

namespace Zitadel\Client\Models;

use Symfony\Component\Serializer\Attribute\SerializedName;

class UserServiceRegisterPasskeyRequest
{
    /** @example null */
    #[SerializedName('userId')]
    public ?string $userId = null;

    /** @example null */
    #[SerializedName('code')]
    public ?\Zitadel\Client\Models\UserServicePasskeyRegistrationCode $code = null;

    /** @example null */
    #[SerializedName('authenticator')]
    public ?\Zitadel\Client\Models\UserServicePasskeyAuthenticator $authenticator = null;

    /** @example null */
    #[SerializedName('domain')]
    public ?string $domain = null;

    /**
     */
    public function __construct(
        ?string $userId = null,
        ?\Zitadel\Client\Models\UserServicePasskeyRegistrationCode $code = null,
        ?\Zitadel\Client\Models\UserServicePasskeyAuthenticator $authenticator = null,
        ?string $domain = null,
    ) {
        $this->userId = $userId;
        $this->code = $code;
        $this->authenticator = $authenticator;
        $this->domain = $domain;
    }
}
