<?php
/**
 * ApplicationServiceApplicationSearchFilter
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zitadel SDK
 *
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;

use \ArrayAccess;
use \Zitadel\Client\ObjectSerializer;

/**
 * ApplicationServiceApplicationSearchFilter Class Doc Comment
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApplicationServiceApplicationSearchFilter implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ApplicationServiceApplicationSearchFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'clientIdFilter' => '\Zitadel\Client\Model\ApplicationServiceClientIDFilter',
        'entityIdFilter' => '\Zitadel\Client\Model\ApplicationServiceEntityIDFilter',
        'nameFilter' => '\Zitadel\Client\Model\ApplicationServiceApplicationNameFilter',
        'projectIdFilter' => '\Zitadel\Client\Model\ApplicationServiceProjectIDFilter',
        'stateFilter' => '\Zitadel\Client\Model\ApplicationServiceApplicationState',
        'typeFilter' => '\Zitadel\Client\Model\ApplicationServiceApplicationType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'clientIdFilter' => null,
        'entityIdFilter' => null,
        'nameFilter' => null,
        'projectIdFilter' => null,
        'stateFilter' => null,
        'typeFilter' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'clientIdFilter' => false,
        'entityIdFilter' => false,
        'nameFilter' => false,
        'projectIdFilter' => false,
        'stateFilter' => false,
        'typeFilter' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clientIdFilter' => 'clientIdFilter',
        'entityIdFilter' => 'entityIdFilter',
        'nameFilter' => 'nameFilter',
        'projectIdFilter' => 'projectIdFilter',
        'stateFilter' => 'stateFilter',
        'typeFilter' => 'typeFilter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clientIdFilter' => 'setClientIdFilter',
        'entityIdFilter' => 'setEntityIdFilter',
        'nameFilter' => 'setNameFilter',
        'projectIdFilter' => 'setProjectIdFilter',
        'stateFilter' => 'setStateFilter',
        'typeFilter' => 'setTypeFilter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clientIdFilter' => 'getClientIdFilter',
        'entityIdFilter' => 'getEntityIdFilter',
        'nameFilter' => 'getNameFilter',
        'projectIdFilter' => 'getProjectIdFilter',
        'stateFilter' => 'getStateFilter',
        'typeFilter' => 'getTypeFilter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clientIdFilter', $data ?? [], null);
        $this->setIfExists('entityIdFilter', $data ?? [], null);
        $this->setIfExists('nameFilter', $data ?? [], null);
        $this->setIfExists('projectIdFilter', $data ?? [], null);
        $this->setIfExists('stateFilter', $data ?? [], null);
        $this->setIfExists('typeFilter', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientIdFilter
     *
     * @return \Zitadel\Client\Model\ApplicationServiceClientIDFilter|null
     */
    public function getClientIdFilter()
    {
        return $this->container['clientIdFilter'];
    }

    /**
     * Sets clientIdFilter
     *
     * @param \Zitadel\Client\Model\ApplicationServiceClientIDFilter|null $clientIdFilter clientIdFilter
     *
     * @return self
     */
    public function setClientIdFilter($clientIdFilter)
    {
        if (is_null($clientIdFilter)) {
            throw new \InvalidArgumentException('non-nullable clientIdFilter cannot be null');
        }
        $this->container['clientIdFilter'] = $clientIdFilter;

        return $this;
    }

    /**
     * Gets entityIdFilter
     *
     * @return \Zitadel\Client\Model\ApplicationServiceEntityIDFilter|null
     */
    public function getEntityIdFilter()
    {
        return $this->container['entityIdFilter'];
    }

    /**
     * Sets entityIdFilter
     *
     * @param \Zitadel\Client\Model\ApplicationServiceEntityIDFilter|null $entityIdFilter entityIdFilter
     *
     * @return self
     */
    public function setEntityIdFilter($entityIdFilter)
    {
        if (is_null($entityIdFilter)) {
            throw new \InvalidArgumentException('non-nullable entityIdFilter cannot be null');
        }
        $this->container['entityIdFilter'] = $entityIdFilter;

        return $this;
    }

    /**
     * Gets nameFilter
     *
     * @return \Zitadel\Client\Model\ApplicationServiceApplicationNameFilter|null
     */
    public function getNameFilter()
    {
        return $this->container['nameFilter'];
    }

    /**
     * Sets nameFilter
     *
     * @param \Zitadel\Client\Model\ApplicationServiceApplicationNameFilter|null $nameFilter nameFilter
     *
     * @return self
     */
    public function setNameFilter($nameFilter)
    {
        if (is_null($nameFilter)) {
            throw new \InvalidArgumentException('non-nullable nameFilter cannot be null');
        }
        $this->container['nameFilter'] = $nameFilter;

        return $this;
    }

    /**
     * Gets projectIdFilter
     *
     * @return \Zitadel\Client\Model\ApplicationServiceProjectIDFilter|null
     */
    public function getProjectIdFilter()
    {
        return $this->container['projectIdFilter'];
    }

    /**
     * Sets projectIdFilter
     *
     * @param \Zitadel\Client\Model\ApplicationServiceProjectIDFilter|null $projectIdFilter projectIdFilter
     *
     * @return self
     */
    public function setProjectIdFilter($projectIdFilter)
    {
        if (is_null($projectIdFilter)) {
            throw new \InvalidArgumentException('non-nullable projectIdFilter cannot be null');
        }
        $this->container['projectIdFilter'] = $projectIdFilter;

        return $this;
    }

    /**
     * Gets stateFilter
     *
     * @return \Zitadel\Client\Model\ApplicationServiceApplicationState|null
     */
    public function getStateFilter()
    {
        return $this->container['stateFilter'];
    }

    /**
     * Sets stateFilter
     *
     * @param \Zitadel\Client\Model\ApplicationServiceApplicationState|null $stateFilter stateFilter
     *
     * @return self
     */
    public function setStateFilter($stateFilter)
    {
        if (is_null($stateFilter)) {
            throw new \InvalidArgumentException('non-nullable stateFilter cannot be null');
        }
        $this->container['stateFilter'] = $stateFilter;

        return $this;
    }

    /**
     * Gets typeFilter
     *
     * @return \Zitadel\Client\Model\ApplicationServiceApplicationType|null
     */
    public function getTypeFilter()
    {
        return $this->container['typeFilter'];
    }

    /**
     * Sets typeFilter
     *
     * @param \Zitadel\Client\Model\ApplicationServiceApplicationType|null $typeFilter typeFilter
     *
     * @return self
     */
    public function setTypeFilter($typeFilter)
    {
        if (is_null($typeFilter)) {
            throw new \InvalidArgumentException('non-nullable typeFilter cannot be null');
        }
        $this->container['typeFilter'] = $typeFilter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


