<?php
/**
 * NoOp200Response4
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zitadel SDK
 *
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;

use \ArrayAccess;
use \Zitadel\Client\ObjectSerializer;

/**
 * NoOp200Response4 Class Doc Comment
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoOp200Response4 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoOp_200_response_4';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'f83cbcd650364bf981df5e981a715601' => '\Zitadel\Client\Model\UserServiceAndQuery',
        '_2c71a3b1Ca6e4083B890Ce7e1417208c' => 'object',
        'd5c89d638d404cc1Bf55D80555c47869' => 'object',
        'c6f1c3a5Af2b42db890c3710b529d4c5' => 'object',
        'dfdd898b63794e2f8c225cafcd3d5ef6' => '\Zitadel\Client\Model\UserServiceAuthFactorU2F',
        '_4bbfd13bC962483fB46f2ee3fffec835' => '\Zitadel\Client\Model\UserServiceDisplayNameQuery',
        'b0c12bff7b7340639e3a247d21b6573c' => '\Zitadel\Client\Model\UserServiceEmailQuery',
        '_88ca59f6A6a747348fe776e79f648e60' => '\Zitadel\Client\Model\UserServiceFirstNameQuery',
        'f110e839Fa114c73AeeaD6660a4723a9' => '\Zitadel\Client\Model\UserServiceHashedPassword',
        'ac724ea0F3ed4fcb999bEe9af910fbe6' => '\Zitadel\Client\Model\UserServiceHumanUser',
        'a3e3b38588a54472B687879df649ca3e' => '\Zitadel\Client\Model\UserServiceIDPIntent',
        '_39c2a13153aa433492a0Ac7338b2ce67' => '\Zitadel\Client\Model\UserServiceIDPLDAPAccessInformation',
        'b742b05fE9ca4dabA96628ac2d0da16c' => '\Zitadel\Client\Model\UserServiceIDPOAuthAccessInformation',
        '_5098155e573f4c4885fe4f3c9c588931' => '\Zitadel\Client\Model\UserServiceIDPSAMLAccessInformation',
        '_0e6081134718441e9482B82d45d55586' => '\Zitadel\Client\Model\UserServiceInUserEmailsQuery',
        'b06ee9a421ac446eB16f9ee6703c52f2' => '\Zitadel\Client\Model\UserServiceInUserIDQuery',
        'c52030ba0a5d48bf8956396a28e6203b' => '\Zitadel\Client\Model\UserServiceLDAPCredentials',
        '_93616c1c65564f8d9446Aa25ddb024fd' => '\Zitadel\Client\Model\UserServiceLastNameQuery',
        '_73c97b6fEcbc46d9B33aC76b0193fa24' => '\Zitadel\Client\Model\UserServiceLoginNameQuery',
        '_9237e11bE85948c799d837be608b578f' => '\Zitadel\Client\Model\UserServiceMachineUser',
        '_41ea4efa714b49a0B7a45ea0accb986d' => '\Zitadel\Client\Model\UserServiceNickNameQuery',
        'a614946e6bd04b26B9474d18205eda35' => '\Zitadel\Client\Model\UserServiceNotQuery',
        '_652fb458324344c1B75a9dcf0b130c7b' => '\Zitadel\Client\Model\UserServiceOrQuery',
        '_0063cccdE3f74f838a9fF9f2f2001fa9' => '\Zitadel\Client\Model\UserServiceOrganizationIdQuery',
        '_5340fb08D5454c8cB47aEcb6bfaa621a' => '\Zitadel\Client\Model\UserServicePassword',
        'ed2e8b696e674202A1b0Ecfd937d2ddf' => '\Zitadel\Client\Model\UserServicePhoneQuery',
        '_9e93d1822acf4856A9166e0d81d39cea' => '\Zitadel\Client\Model\UserServiceRedirectURLs',
        '_1fc91c19Eef245c885146c624f785660' => 'object',
        'c13ba8a142834a8c9291126631d1ad41' => 'object',
        '_3e19c9726f3f4eb68ca296cd9f2087ea' => 'object',
        '_74045de494c84118B0a2E40a23bf4399' => 'object',
        'f2f1dabe90ec4e66Bb06308dda585c74' => 'object',
        '_98d4b310Bd3a4be3954e393580550f8e' => '\Zitadel\Client\Model\UserServiceSendEmailVerificationCode',
        '_9dd39bba3a0747329fbaB304fd0e5a88' => '\Zitadel\Client\Model\UserServiceSendInviteCode',
        '_236b67a626aa4cf79c3dF15e31eef06b' => '\Zitadel\Client\Model\UserServiceSendPasskeyRegistrationLink',
        '_8a890a58C2fc478486de6d34c866bc6d' => '\Zitadel\Client\Model\UserServiceSendPasswordResetLink',
        '_80a2ea0167c94c08A15d8aa8c5f65814' => 'object',
        'fb1210fc309744c9AdfeB5f65ae80aad' => '\Zitadel\Client\Model\UserServiceStateQuery',
        '_5453af57519541e1A89a815aefafd209' => '\Zitadel\Client\Model\UserServiceTypeQuery',
        'ffb17b46E3dc4eaaB8fe611e1ace506d' => '\Zitadel\Client\Model\UserServiceUserNameQuery'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'f83cbcd650364bf981df5e981a715601' => null,
        '_2c71a3b1Ca6e4083B890Ce7e1417208c' => null,
        'd5c89d638d404cc1Bf55D80555c47869' => null,
        'c6f1c3a5Af2b42db890c3710b529d4c5' => null,
        'dfdd898b63794e2f8c225cafcd3d5ef6' => null,
        '_4bbfd13bC962483fB46f2ee3fffec835' => null,
        'b0c12bff7b7340639e3a247d21b6573c' => null,
        '_88ca59f6A6a747348fe776e79f648e60' => null,
        'f110e839Fa114c73AeeaD6660a4723a9' => null,
        'ac724ea0F3ed4fcb999bEe9af910fbe6' => null,
        'a3e3b38588a54472B687879df649ca3e' => null,
        '_39c2a13153aa433492a0Ac7338b2ce67' => null,
        'b742b05fE9ca4dabA96628ac2d0da16c' => null,
        '_5098155e573f4c4885fe4f3c9c588931' => null,
        '_0e6081134718441e9482B82d45d55586' => null,
        'b06ee9a421ac446eB16f9ee6703c52f2' => null,
        'c52030ba0a5d48bf8956396a28e6203b' => null,
        '_93616c1c65564f8d9446Aa25ddb024fd' => null,
        '_73c97b6fEcbc46d9B33aC76b0193fa24' => null,
        '_9237e11bE85948c799d837be608b578f' => null,
        '_41ea4efa714b49a0B7a45ea0accb986d' => null,
        'a614946e6bd04b26B9474d18205eda35' => null,
        '_652fb458324344c1B75a9dcf0b130c7b' => null,
        '_0063cccdE3f74f838a9fF9f2f2001fa9' => null,
        '_5340fb08D5454c8cB47aEcb6bfaa621a' => null,
        'ed2e8b696e674202A1b0Ecfd937d2ddf' => null,
        '_9e93d1822acf4856A9166e0d81d39cea' => null,
        '_1fc91c19Eef245c885146c624f785660' => null,
        'c13ba8a142834a8c9291126631d1ad41' => null,
        '_3e19c9726f3f4eb68ca296cd9f2087ea' => null,
        '_74045de494c84118B0a2E40a23bf4399' => null,
        'f2f1dabe90ec4e66Bb06308dda585c74' => null,
        '_98d4b310Bd3a4be3954e393580550f8e' => null,
        '_9dd39bba3a0747329fbaB304fd0e5a88' => null,
        '_236b67a626aa4cf79c3dF15e31eef06b' => null,
        '_8a890a58C2fc478486de6d34c866bc6d' => null,
        '_80a2ea0167c94c08A15d8aa8c5f65814' => null,
        'fb1210fc309744c9AdfeB5f65ae80aad' => null,
        '_5453af57519541e1A89a815aefafd209' => null,
        'ffb17b46E3dc4eaaB8fe611e1ace506d' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'f83cbcd650364bf981df5e981a715601' => false,
        '_2c71a3b1Ca6e4083B890Ce7e1417208c' => false,
        'd5c89d638d404cc1Bf55D80555c47869' => false,
        'c6f1c3a5Af2b42db890c3710b529d4c5' => false,
        'dfdd898b63794e2f8c225cafcd3d5ef6' => false,
        '_4bbfd13bC962483fB46f2ee3fffec835' => false,
        'b0c12bff7b7340639e3a247d21b6573c' => false,
        '_88ca59f6A6a747348fe776e79f648e60' => false,
        'f110e839Fa114c73AeeaD6660a4723a9' => false,
        'ac724ea0F3ed4fcb999bEe9af910fbe6' => false,
        'a3e3b38588a54472B687879df649ca3e' => false,
        '_39c2a13153aa433492a0Ac7338b2ce67' => false,
        'b742b05fE9ca4dabA96628ac2d0da16c' => false,
        '_5098155e573f4c4885fe4f3c9c588931' => false,
        '_0e6081134718441e9482B82d45d55586' => false,
        'b06ee9a421ac446eB16f9ee6703c52f2' => false,
        'c52030ba0a5d48bf8956396a28e6203b' => false,
        '_93616c1c65564f8d9446Aa25ddb024fd' => false,
        '_73c97b6fEcbc46d9B33aC76b0193fa24' => false,
        '_9237e11bE85948c799d837be608b578f' => false,
        '_41ea4efa714b49a0B7a45ea0accb986d' => false,
        'a614946e6bd04b26B9474d18205eda35' => false,
        '_652fb458324344c1B75a9dcf0b130c7b' => false,
        '_0063cccdE3f74f838a9fF9f2f2001fa9' => false,
        '_5340fb08D5454c8cB47aEcb6bfaa621a' => false,
        'ed2e8b696e674202A1b0Ecfd937d2ddf' => false,
        '_9e93d1822acf4856A9166e0d81d39cea' => false,
        '_1fc91c19Eef245c885146c624f785660' => false,
        'c13ba8a142834a8c9291126631d1ad41' => false,
        '_3e19c9726f3f4eb68ca296cd9f2087ea' => false,
        '_74045de494c84118B0a2E40a23bf4399' => false,
        'f2f1dabe90ec4e66Bb06308dda585c74' => false,
        '_98d4b310Bd3a4be3954e393580550f8e' => false,
        '_9dd39bba3a0747329fbaB304fd0e5a88' => false,
        '_236b67a626aa4cf79c3dF15e31eef06b' => false,
        '_8a890a58C2fc478486de6d34c866bc6d' => false,
        '_80a2ea0167c94c08A15d8aa8c5f65814' => false,
        'fb1210fc309744c9AdfeB5f65ae80aad' => false,
        '_5453af57519541e1A89a815aefafd209' => false,
        'ffb17b46E3dc4eaaB8fe611e1ace506d' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'f83cbcd650364bf981df5e981a715601' => 'f83cbcd6-5036-4bf9-81df-5e981a715601',
        '_2c71a3b1Ca6e4083B890Ce7e1417208c' => '2c71a3b1-ca6e-4083-b890-ce7e1417208c',
        'd5c89d638d404cc1Bf55D80555c47869' => 'd5c89d63-8d40-4cc1-bf55-d80555c47869',
        'c6f1c3a5Af2b42db890c3710b529d4c5' => 'c6f1c3a5-af2b-42db-890c-3710b529d4c5',
        'dfdd898b63794e2f8c225cafcd3d5ef6' => 'dfdd898b-6379-4e2f-8c22-5cafcd3d5ef6',
        '_4bbfd13bC962483fB46f2ee3fffec835' => '4bbfd13b-c962-483f-b46f-2ee3fffec835',
        'b0c12bff7b7340639e3a247d21b6573c' => 'b0c12bff-7b73-4063-9e3a-247d21b6573c',
        '_88ca59f6A6a747348fe776e79f648e60' => '88ca59f6-a6a7-4734-8fe7-76e79f648e60',
        'f110e839Fa114c73AeeaD6660a4723a9' => 'f110e839-fa11-4c73-aeea-d6660a4723a9',
        'ac724ea0F3ed4fcb999bEe9af910fbe6' => 'ac724ea0-f3ed-4fcb-999b-ee9af910fbe6',
        'a3e3b38588a54472B687879df649ca3e' => 'a3e3b385-88a5-4472-b687-879df649ca3e',
        '_39c2a13153aa433492a0Ac7338b2ce67' => '39c2a131-53aa-4334-92a0-ac7338b2ce67',
        'b742b05fE9ca4dabA96628ac2d0da16c' => 'b742b05f-e9ca-4dab-a966-28ac2d0da16c',
        '_5098155e573f4c4885fe4f3c9c588931' => '5098155e-573f-4c48-85fe-4f3c9c588931',
        '_0e6081134718441e9482B82d45d55586' => '0e608113-4718-441e-9482-b82d45d55586',
        'b06ee9a421ac446eB16f9ee6703c52f2' => 'b06ee9a4-21ac-446e-b16f-9ee6703c52f2',
        'c52030ba0a5d48bf8956396a28e6203b' => 'c52030ba-0a5d-48bf-8956-396a28e6203b',
        '_93616c1c65564f8d9446Aa25ddb024fd' => '93616c1c-6556-4f8d-9446-aa25ddb024fd',
        '_73c97b6fEcbc46d9B33aC76b0193fa24' => '73c97b6f-ecbc-46d9-b33a-c76b0193fa24',
        '_9237e11bE85948c799d837be608b578f' => '9237e11b-e859-48c7-99d8-37be608b578f',
        '_41ea4efa714b49a0B7a45ea0accb986d' => '41ea4efa-714b-49a0-b7a4-5ea0accb986d',
        'a614946e6bd04b26B9474d18205eda35' => 'a614946e-6bd0-4b26-b947-4d18205eda35',
        '_652fb458324344c1B75a9dcf0b130c7b' => '652fb458-3243-44c1-b75a-9dcf0b130c7b',
        '_0063cccdE3f74f838a9fF9f2f2001fa9' => '0063cccd-e3f7-4f83-8a9f-f9f2f2001fa9',
        '_5340fb08D5454c8cB47aEcb6bfaa621a' => '5340fb08-d545-4c8c-b47a-ecb6bfaa621a',
        'ed2e8b696e674202A1b0Ecfd937d2ddf' => 'ed2e8b69-6e67-4202-a1b0-ecfd937d2ddf',
        '_9e93d1822acf4856A9166e0d81d39cea' => '9e93d182-2acf-4856-a916-6e0d81d39cea',
        '_1fc91c19Eef245c885146c624f785660' => '1fc91c19-eef2-45c8-8514-6c624f785660',
        'c13ba8a142834a8c9291126631d1ad41' => 'c13ba8a1-4283-4a8c-9291-126631d1ad41',
        '_3e19c9726f3f4eb68ca296cd9f2087ea' => '3e19c972-6f3f-4eb6-8ca2-96cd9f2087ea',
        '_74045de494c84118B0a2E40a23bf4399' => '74045de4-94c8-4118-b0a2-e40a23bf4399',
        'f2f1dabe90ec4e66Bb06308dda585c74' => 'f2f1dabe-90ec-4e66-bb06-308dda585c74',
        '_98d4b310Bd3a4be3954e393580550f8e' => '98d4b310-bd3a-4be3-954e-393580550f8e',
        '_9dd39bba3a0747329fbaB304fd0e5a88' => '9dd39bba-3a07-4732-9fba-b304fd0e5a88',
        '_236b67a626aa4cf79c3dF15e31eef06b' => '236b67a6-26aa-4cf7-9c3d-f15e31eef06b',
        '_8a890a58C2fc478486de6d34c866bc6d' => '8a890a58-c2fc-4784-86de-6d34c866bc6d',
        '_80a2ea0167c94c08A15d8aa8c5f65814' => '80a2ea01-67c9-4c08-a15d-8aa8c5f65814',
        'fb1210fc309744c9AdfeB5f65ae80aad' => 'fb1210fc-3097-44c9-adfe-b5f65ae80aad',
        '_5453af57519541e1A89a815aefafd209' => '5453af57-5195-41e1-a89a-815aefafd209',
        'ffb17b46E3dc4eaaB8fe611e1ace506d' => 'ffb17b46-e3dc-4eaa-b8fe-611e1ace506d'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'f83cbcd650364bf981df5e981a715601' => 'setF83cbcd650364bf981df5e981a715601',
        '_2c71a3b1Ca6e4083B890Ce7e1417208c' => 'set2c71a3b1Ca6e4083B890Ce7e1417208c',
        'd5c89d638d404cc1Bf55D80555c47869' => 'setD5c89d638d404cc1Bf55D80555c47869',
        'c6f1c3a5Af2b42db890c3710b529d4c5' => 'setC6f1c3a5Af2b42db890c3710b529d4c5',
        'dfdd898b63794e2f8c225cafcd3d5ef6' => 'setDfdd898b63794e2f8c225cafcd3d5ef6',
        '_4bbfd13bC962483fB46f2ee3fffec835' => 'set4bbfd13bC962483fB46f2ee3fffec835',
        'b0c12bff7b7340639e3a247d21b6573c' => 'setB0c12bff7b7340639e3a247d21b6573c',
        '_88ca59f6A6a747348fe776e79f648e60' => 'set88ca59f6A6a747348fe776e79f648e60',
        'f110e839Fa114c73AeeaD6660a4723a9' => 'setF110e839Fa114c73AeeaD6660a4723a9',
        'ac724ea0F3ed4fcb999bEe9af910fbe6' => 'setAc724ea0F3ed4fcb999bEe9af910fbe6',
        'a3e3b38588a54472B687879df649ca3e' => 'setA3e3b38588a54472B687879df649ca3e',
        '_39c2a13153aa433492a0Ac7338b2ce67' => 'set39c2a13153aa433492a0Ac7338b2ce67',
        'b742b05fE9ca4dabA96628ac2d0da16c' => 'setB742b05fE9ca4dabA96628ac2d0da16c',
        '_5098155e573f4c4885fe4f3c9c588931' => 'set5098155e573f4c4885fe4f3c9c588931',
        '_0e6081134718441e9482B82d45d55586' => 'set0e6081134718441e9482B82d45d55586',
        'b06ee9a421ac446eB16f9ee6703c52f2' => 'setB06ee9a421ac446eB16f9ee6703c52f2',
        'c52030ba0a5d48bf8956396a28e6203b' => 'setC52030ba0a5d48bf8956396a28e6203b',
        '_93616c1c65564f8d9446Aa25ddb024fd' => 'set93616c1c65564f8d9446Aa25ddb024fd',
        '_73c97b6fEcbc46d9B33aC76b0193fa24' => 'set73c97b6fEcbc46d9B33aC76b0193fa24',
        '_9237e11bE85948c799d837be608b578f' => 'set9237e11bE85948c799d837be608b578f',
        '_41ea4efa714b49a0B7a45ea0accb986d' => 'set41ea4efa714b49a0B7a45ea0accb986d',
        'a614946e6bd04b26B9474d18205eda35' => 'setA614946e6bd04b26B9474d18205eda35',
        '_652fb458324344c1B75a9dcf0b130c7b' => 'set652fb458324344c1B75a9dcf0b130c7b',
        '_0063cccdE3f74f838a9fF9f2f2001fa9' => 'set0063cccdE3f74f838a9fF9f2f2001fa9',
        '_5340fb08D5454c8cB47aEcb6bfaa621a' => 'set5340fb08D5454c8cB47aEcb6bfaa621a',
        'ed2e8b696e674202A1b0Ecfd937d2ddf' => 'setEd2e8b696e674202A1b0Ecfd937d2ddf',
        '_9e93d1822acf4856A9166e0d81d39cea' => 'set9e93d1822acf4856A9166e0d81d39cea',
        '_1fc91c19Eef245c885146c624f785660' => 'set1fc91c19Eef245c885146c624f785660',
        'c13ba8a142834a8c9291126631d1ad41' => 'setC13ba8a142834a8c9291126631d1ad41',
        '_3e19c9726f3f4eb68ca296cd9f2087ea' => 'set3e19c9726f3f4eb68ca296cd9f2087ea',
        '_74045de494c84118B0a2E40a23bf4399' => 'set74045de494c84118B0a2E40a23bf4399',
        'f2f1dabe90ec4e66Bb06308dda585c74' => 'setF2f1dabe90ec4e66Bb06308dda585c74',
        '_98d4b310Bd3a4be3954e393580550f8e' => 'set98d4b310Bd3a4be3954e393580550f8e',
        '_9dd39bba3a0747329fbaB304fd0e5a88' => 'set9dd39bba3a0747329fbaB304fd0e5a88',
        '_236b67a626aa4cf79c3dF15e31eef06b' => 'set236b67a626aa4cf79c3dF15e31eef06b',
        '_8a890a58C2fc478486de6d34c866bc6d' => 'set8a890a58C2fc478486de6d34c866bc6d',
        '_80a2ea0167c94c08A15d8aa8c5f65814' => 'set80a2ea0167c94c08A15d8aa8c5f65814',
        'fb1210fc309744c9AdfeB5f65ae80aad' => 'setFb1210fc309744c9AdfeB5f65ae80aad',
        '_5453af57519541e1A89a815aefafd209' => 'set5453af57519541e1A89a815aefafd209',
        'ffb17b46E3dc4eaaB8fe611e1ace506d' => 'setFfb17b46E3dc4eaaB8fe611e1ace506d'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'f83cbcd650364bf981df5e981a715601' => 'getF83cbcd650364bf981df5e981a715601',
        '_2c71a3b1Ca6e4083B890Ce7e1417208c' => 'get2c71a3b1Ca6e4083B890Ce7e1417208c',
        'd5c89d638d404cc1Bf55D80555c47869' => 'getD5c89d638d404cc1Bf55D80555c47869',
        'c6f1c3a5Af2b42db890c3710b529d4c5' => 'getC6f1c3a5Af2b42db890c3710b529d4c5',
        'dfdd898b63794e2f8c225cafcd3d5ef6' => 'getDfdd898b63794e2f8c225cafcd3d5ef6',
        '_4bbfd13bC962483fB46f2ee3fffec835' => 'get4bbfd13bC962483fB46f2ee3fffec835',
        'b0c12bff7b7340639e3a247d21b6573c' => 'getB0c12bff7b7340639e3a247d21b6573c',
        '_88ca59f6A6a747348fe776e79f648e60' => 'get88ca59f6A6a747348fe776e79f648e60',
        'f110e839Fa114c73AeeaD6660a4723a9' => 'getF110e839Fa114c73AeeaD6660a4723a9',
        'ac724ea0F3ed4fcb999bEe9af910fbe6' => 'getAc724ea0F3ed4fcb999bEe9af910fbe6',
        'a3e3b38588a54472B687879df649ca3e' => 'getA3e3b38588a54472B687879df649ca3e',
        '_39c2a13153aa433492a0Ac7338b2ce67' => 'get39c2a13153aa433492a0Ac7338b2ce67',
        'b742b05fE9ca4dabA96628ac2d0da16c' => 'getB742b05fE9ca4dabA96628ac2d0da16c',
        '_5098155e573f4c4885fe4f3c9c588931' => 'get5098155e573f4c4885fe4f3c9c588931',
        '_0e6081134718441e9482B82d45d55586' => 'get0e6081134718441e9482B82d45d55586',
        'b06ee9a421ac446eB16f9ee6703c52f2' => 'getB06ee9a421ac446eB16f9ee6703c52f2',
        'c52030ba0a5d48bf8956396a28e6203b' => 'getC52030ba0a5d48bf8956396a28e6203b',
        '_93616c1c65564f8d9446Aa25ddb024fd' => 'get93616c1c65564f8d9446Aa25ddb024fd',
        '_73c97b6fEcbc46d9B33aC76b0193fa24' => 'get73c97b6fEcbc46d9B33aC76b0193fa24',
        '_9237e11bE85948c799d837be608b578f' => 'get9237e11bE85948c799d837be608b578f',
        '_41ea4efa714b49a0B7a45ea0accb986d' => 'get41ea4efa714b49a0B7a45ea0accb986d',
        'a614946e6bd04b26B9474d18205eda35' => 'getA614946e6bd04b26B9474d18205eda35',
        '_652fb458324344c1B75a9dcf0b130c7b' => 'get652fb458324344c1B75a9dcf0b130c7b',
        '_0063cccdE3f74f838a9fF9f2f2001fa9' => 'get0063cccdE3f74f838a9fF9f2f2001fa9',
        '_5340fb08D5454c8cB47aEcb6bfaa621a' => 'get5340fb08D5454c8cB47aEcb6bfaa621a',
        'ed2e8b696e674202A1b0Ecfd937d2ddf' => 'getEd2e8b696e674202A1b0Ecfd937d2ddf',
        '_9e93d1822acf4856A9166e0d81d39cea' => 'get9e93d1822acf4856A9166e0d81d39cea',
        '_1fc91c19Eef245c885146c624f785660' => 'get1fc91c19Eef245c885146c624f785660',
        'c13ba8a142834a8c9291126631d1ad41' => 'getC13ba8a142834a8c9291126631d1ad41',
        '_3e19c9726f3f4eb68ca296cd9f2087ea' => 'get3e19c9726f3f4eb68ca296cd9f2087ea',
        '_74045de494c84118B0a2E40a23bf4399' => 'get74045de494c84118B0a2E40a23bf4399',
        'f2f1dabe90ec4e66Bb06308dda585c74' => 'getF2f1dabe90ec4e66Bb06308dda585c74',
        '_98d4b310Bd3a4be3954e393580550f8e' => 'get98d4b310Bd3a4be3954e393580550f8e',
        '_9dd39bba3a0747329fbaB304fd0e5a88' => 'get9dd39bba3a0747329fbaB304fd0e5a88',
        '_236b67a626aa4cf79c3dF15e31eef06b' => 'get236b67a626aa4cf79c3dF15e31eef06b',
        '_8a890a58C2fc478486de6d34c866bc6d' => 'get8a890a58C2fc478486de6d34c866bc6d',
        '_80a2ea0167c94c08A15d8aa8c5f65814' => 'get80a2ea0167c94c08A15d8aa8c5f65814',
        'fb1210fc309744c9AdfeB5f65ae80aad' => 'getFb1210fc309744c9AdfeB5f65ae80aad',
        '_5453af57519541e1A89a815aefafd209' => 'get5453af57519541e1A89a815aefafd209',
        'ffb17b46E3dc4eaaB8fe611e1ace506d' => 'getFfb17b46E3dc4eaaB8fe611e1ace506d'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('f83cbcd650364bf981df5e981a715601', $data ?? [], null);
        $this->setIfExists('_2c71a3b1Ca6e4083B890Ce7e1417208c', $data ?? [], null);
        $this->setIfExists('d5c89d638d404cc1Bf55D80555c47869', $data ?? [], null);
        $this->setIfExists('c6f1c3a5Af2b42db890c3710b529d4c5', $data ?? [], null);
        $this->setIfExists('dfdd898b63794e2f8c225cafcd3d5ef6', $data ?? [], null);
        $this->setIfExists('_4bbfd13bC962483fB46f2ee3fffec835', $data ?? [], null);
        $this->setIfExists('b0c12bff7b7340639e3a247d21b6573c', $data ?? [], null);
        $this->setIfExists('_88ca59f6A6a747348fe776e79f648e60', $data ?? [], null);
        $this->setIfExists('f110e839Fa114c73AeeaD6660a4723a9', $data ?? [], null);
        $this->setIfExists('ac724ea0F3ed4fcb999bEe9af910fbe6', $data ?? [], null);
        $this->setIfExists('a3e3b38588a54472B687879df649ca3e', $data ?? [], null);
        $this->setIfExists('_39c2a13153aa433492a0Ac7338b2ce67', $data ?? [], null);
        $this->setIfExists('b742b05fE9ca4dabA96628ac2d0da16c', $data ?? [], null);
        $this->setIfExists('_5098155e573f4c4885fe4f3c9c588931', $data ?? [], null);
        $this->setIfExists('_0e6081134718441e9482B82d45d55586', $data ?? [], null);
        $this->setIfExists('b06ee9a421ac446eB16f9ee6703c52f2', $data ?? [], null);
        $this->setIfExists('c52030ba0a5d48bf8956396a28e6203b', $data ?? [], null);
        $this->setIfExists('_93616c1c65564f8d9446Aa25ddb024fd', $data ?? [], null);
        $this->setIfExists('_73c97b6fEcbc46d9B33aC76b0193fa24', $data ?? [], null);
        $this->setIfExists('_9237e11bE85948c799d837be608b578f', $data ?? [], null);
        $this->setIfExists('_41ea4efa714b49a0B7a45ea0accb986d', $data ?? [], null);
        $this->setIfExists('a614946e6bd04b26B9474d18205eda35', $data ?? [], null);
        $this->setIfExists('_652fb458324344c1B75a9dcf0b130c7b', $data ?? [], null);
        $this->setIfExists('_0063cccdE3f74f838a9fF9f2f2001fa9', $data ?? [], null);
        $this->setIfExists('_5340fb08D5454c8cB47aEcb6bfaa621a', $data ?? [], null);
        $this->setIfExists('ed2e8b696e674202A1b0Ecfd937d2ddf', $data ?? [], null);
        $this->setIfExists('_9e93d1822acf4856A9166e0d81d39cea', $data ?? [], null);
        $this->setIfExists('_1fc91c19Eef245c885146c624f785660', $data ?? [], null);
        $this->setIfExists('c13ba8a142834a8c9291126631d1ad41', $data ?? [], null);
        $this->setIfExists('_3e19c9726f3f4eb68ca296cd9f2087ea', $data ?? [], null);
        $this->setIfExists('_74045de494c84118B0a2E40a23bf4399', $data ?? [], null);
        $this->setIfExists('f2f1dabe90ec4e66Bb06308dda585c74', $data ?? [], null);
        $this->setIfExists('_98d4b310Bd3a4be3954e393580550f8e', $data ?? [], null);
        $this->setIfExists('_9dd39bba3a0747329fbaB304fd0e5a88', $data ?? [], null);
        $this->setIfExists('_236b67a626aa4cf79c3dF15e31eef06b', $data ?? [], null);
        $this->setIfExists('_8a890a58C2fc478486de6d34c866bc6d', $data ?? [], null);
        $this->setIfExists('_80a2ea0167c94c08A15d8aa8c5f65814', $data ?? [], null);
        $this->setIfExists('fb1210fc309744c9AdfeB5f65ae80aad', $data ?? [], null);
        $this->setIfExists('_5453af57519541e1A89a815aefafd209', $data ?? [], null);
        $this->setIfExists('ffb17b46E3dc4eaaB8fe611e1ace506d', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets f83cbcd650364bf981df5e981a715601
     *
     * @return \Zitadel\Client\Model\UserServiceAndQuery|null
     */
    public function getF83cbcd650364bf981df5e981a715601()
    {
        return $this->container['f83cbcd650364bf981df5e981a715601'];
    }

    /**
     * Sets f83cbcd650364bf981df5e981a715601
     *
     * @param \Zitadel\Client\Model\UserServiceAndQuery|null $f83cbcd650364bf981df5e981a715601 f83cbcd650364bf981df5e981a715601
     *
     * @return self
     */
    public function setF83cbcd650364bf981df5e981a715601($f83cbcd650364bf981df5e981a715601)
    {
        if (is_null($f83cbcd650364bf981df5e981a715601)) {
            throw new \InvalidArgumentException('non-nullable f83cbcd650364bf981df5e981a715601 cannot be null');
        }
        $this->container['f83cbcd650364bf981df5e981a715601'] = $f83cbcd650364bf981df5e981a715601;

        return $this;
    }

    /**
     * Gets _2c71a3b1Ca6e4083B890Ce7e1417208c
     *
     * @return object|null
     */
    public function get2c71a3b1Ca6e4083B890Ce7e1417208c()
    {
        return $this->container['_2c71a3b1Ca6e4083B890Ce7e1417208c'];
    }

    /**
     * Sets _2c71a3b1Ca6e4083B890Ce7e1417208c
     *
     * @param object|null $_2c71a3b1Ca6e4083B890Ce7e1417208c _2c71a3b1Ca6e4083B890Ce7e1417208c
     *
     * @return self
     */
    public function set2c71a3b1Ca6e4083B890Ce7e1417208c($_2c71a3b1Ca6e4083B890Ce7e1417208c)
    {
        if (is_null($_2c71a3b1Ca6e4083B890Ce7e1417208c)) {
            throw new \InvalidArgumentException('non-nullable _2c71a3b1Ca6e4083B890Ce7e1417208c cannot be null');
        }
        $this->container['_2c71a3b1Ca6e4083B890Ce7e1417208c'] = $_2c71a3b1Ca6e4083B890Ce7e1417208c;

        return $this;
    }

    /**
     * Gets d5c89d638d404cc1Bf55D80555c47869
     *
     * @return object|null
     */
    public function getD5c89d638d404cc1Bf55D80555c47869()
    {
        return $this->container['d5c89d638d404cc1Bf55D80555c47869'];
    }

    /**
     * Sets d5c89d638d404cc1Bf55D80555c47869
     *
     * @param object|null $d5c89d638d404cc1Bf55D80555c47869 d5c89d638d404cc1Bf55D80555c47869
     *
     * @return self
     */
    public function setD5c89d638d404cc1Bf55D80555c47869($d5c89d638d404cc1Bf55D80555c47869)
    {
        if (is_null($d5c89d638d404cc1Bf55D80555c47869)) {
            throw new \InvalidArgumentException('non-nullable d5c89d638d404cc1Bf55D80555c47869 cannot be null');
        }
        $this->container['d5c89d638d404cc1Bf55D80555c47869'] = $d5c89d638d404cc1Bf55D80555c47869;

        return $this;
    }

    /**
     * Gets c6f1c3a5Af2b42db890c3710b529d4c5
     *
     * @return object|null
     */
    public function getC6f1c3a5Af2b42db890c3710b529d4c5()
    {
        return $this->container['c6f1c3a5Af2b42db890c3710b529d4c5'];
    }

    /**
     * Sets c6f1c3a5Af2b42db890c3710b529d4c5
     *
     * @param object|null $c6f1c3a5Af2b42db890c3710b529d4c5 c6f1c3a5Af2b42db890c3710b529d4c5
     *
     * @return self
     */
    public function setC6f1c3a5Af2b42db890c3710b529d4c5($c6f1c3a5Af2b42db890c3710b529d4c5)
    {
        if (is_null($c6f1c3a5Af2b42db890c3710b529d4c5)) {
            throw new \InvalidArgumentException('non-nullable c6f1c3a5Af2b42db890c3710b529d4c5 cannot be null');
        }
        $this->container['c6f1c3a5Af2b42db890c3710b529d4c5'] = $c6f1c3a5Af2b42db890c3710b529d4c5;

        return $this;
    }

    /**
     * Gets dfdd898b63794e2f8c225cafcd3d5ef6
     *
     * @return \Zitadel\Client\Model\UserServiceAuthFactorU2F|null
     */
    public function getDfdd898b63794e2f8c225cafcd3d5ef6()
    {
        return $this->container['dfdd898b63794e2f8c225cafcd3d5ef6'];
    }

    /**
     * Sets dfdd898b63794e2f8c225cafcd3d5ef6
     *
     * @param \Zitadel\Client\Model\UserServiceAuthFactorU2F|null $dfdd898b63794e2f8c225cafcd3d5ef6 dfdd898b63794e2f8c225cafcd3d5ef6
     *
     * @return self
     */
    public function setDfdd898b63794e2f8c225cafcd3d5ef6($dfdd898b63794e2f8c225cafcd3d5ef6)
    {
        if (is_null($dfdd898b63794e2f8c225cafcd3d5ef6)) {
            throw new \InvalidArgumentException('non-nullable dfdd898b63794e2f8c225cafcd3d5ef6 cannot be null');
        }
        $this->container['dfdd898b63794e2f8c225cafcd3d5ef6'] = $dfdd898b63794e2f8c225cafcd3d5ef6;

        return $this;
    }

    /**
     * Gets _4bbfd13bC962483fB46f2ee3fffec835
     *
     * @return \Zitadel\Client\Model\UserServiceDisplayNameQuery|null
     */
    public function get4bbfd13bC962483fB46f2ee3fffec835()
    {
        return $this->container['_4bbfd13bC962483fB46f2ee3fffec835'];
    }

    /**
     * Sets _4bbfd13bC962483fB46f2ee3fffec835
     *
     * @param \Zitadel\Client\Model\UserServiceDisplayNameQuery|null $_4bbfd13bC962483fB46f2ee3fffec835 _4bbfd13bC962483fB46f2ee3fffec835
     *
     * @return self
     */
    public function set4bbfd13bC962483fB46f2ee3fffec835($_4bbfd13bC962483fB46f2ee3fffec835)
    {
        if (is_null($_4bbfd13bC962483fB46f2ee3fffec835)) {
            throw new \InvalidArgumentException('non-nullable _4bbfd13bC962483fB46f2ee3fffec835 cannot be null');
        }
        $this->container['_4bbfd13bC962483fB46f2ee3fffec835'] = $_4bbfd13bC962483fB46f2ee3fffec835;

        return $this;
    }

    /**
     * Gets b0c12bff7b7340639e3a247d21b6573c
     *
     * @return \Zitadel\Client\Model\UserServiceEmailQuery|null
     */
    public function getB0c12bff7b7340639e3a247d21b6573c()
    {
        return $this->container['b0c12bff7b7340639e3a247d21b6573c'];
    }

    /**
     * Sets b0c12bff7b7340639e3a247d21b6573c
     *
     * @param \Zitadel\Client\Model\UserServiceEmailQuery|null $b0c12bff7b7340639e3a247d21b6573c b0c12bff7b7340639e3a247d21b6573c
     *
     * @return self
     */
    public function setB0c12bff7b7340639e3a247d21b6573c($b0c12bff7b7340639e3a247d21b6573c)
    {
        if (is_null($b0c12bff7b7340639e3a247d21b6573c)) {
            throw new \InvalidArgumentException('non-nullable b0c12bff7b7340639e3a247d21b6573c cannot be null');
        }
        $this->container['b0c12bff7b7340639e3a247d21b6573c'] = $b0c12bff7b7340639e3a247d21b6573c;

        return $this;
    }

    /**
     * Gets _88ca59f6A6a747348fe776e79f648e60
     *
     * @return \Zitadel\Client\Model\UserServiceFirstNameQuery|null
     */
    public function get88ca59f6A6a747348fe776e79f648e60()
    {
        return $this->container['_88ca59f6A6a747348fe776e79f648e60'];
    }

    /**
     * Sets _88ca59f6A6a747348fe776e79f648e60
     *
     * @param \Zitadel\Client\Model\UserServiceFirstNameQuery|null $_88ca59f6A6a747348fe776e79f648e60 _88ca59f6A6a747348fe776e79f648e60
     *
     * @return self
     */
    public function set88ca59f6A6a747348fe776e79f648e60($_88ca59f6A6a747348fe776e79f648e60)
    {
        if (is_null($_88ca59f6A6a747348fe776e79f648e60)) {
            throw new \InvalidArgumentException('non-nullable _88ca59f6A6a747348fe776e79f648e60 cannot be null');
        }
        $this->container['_88ca59f6A6a747348fe776e79f648e60'] = $_88ca59f6A6a747348fe776e79f648e60;

        return $this;
    }

    /**
     * Gets f110e839Fa114c73AeeaD6660a4723a9
     *
     * @return \Zitadel\Client\Model\UserServiceHashedPassword|null
     */
    public function getF110e839Fa114c73AeeaD6660a4723a9()
    {
        return $this->container['f110e839Fa114c73AeeaD6660a4723a9'];
    }

    /**
     * Sets f110e839Fa114c73AeeaD6660a4723a9
     *
     * @param \Zitadel\Client\Model\UserServiceHashedPassword|null $f110e839Fa114c73AeeaD6660a4723a9 f110e839Fa114c73AeeaD6660a4723a9
     *
     * @return self
     */
    public function setF110e839Fa114c73AeeaD6660a4723a9($f110e839Fa114c73AeeaD6660a4723a9)
    {
        if (is_null($f110e839Fa114c73AeeaD6660a4723a9)) {
            throw new \InvalidArgumentException('non-nullable f110e839Fa114c73AeeaD6660a4723a9 cannot be null');
        }
        $this->container['f110e839Fa114c73AeeaD6660a4723a9'] = $f110e839Fa114c73AeeaD6660a4723a9;

        return $this;
    }

    /**
     * Gets ac724ea0F3ed4fcb999bEe9af910fbe6
     *
     * @return \Zitadel\Client\Model\UserServiceHumanUser|null
     */
    public function getAc724ea0F3ed4fcb999bEe9af910fbe6()
    {
        return $this->container['ac724ea0F3ed4fcb999bEe9af910fbe6'];
    }

    /**
     * Sets ac724ea0F3ed4fcb999bEe9af910fbe6
     *
     * @param \Zitadel\Client\Model\UserServiceHumanUser|null $ac724ea0F3ed4fcb999bEe9af910fbe6 ac724ea0F3ed4fcb999bEe9af910fbe6
     *
     * @return self
     */
    public function setAc724ea0F3ed4fcb999bEe9af910fbe6($ac724ea0F3ed4fcb999bEe9af910fbe6)
    {
        if (is_null($ac724ea0F3ed4fcb999bEe9af910fbe6)) {
            throw new \InvalidArgumentException('non-nullable ac724ea0F3ed4fcb999bEe9af910fbe6 cannot be null');
        }
        $this->container['ac724ea0F3ed4fcb999bEe9af910fbe6'] = $ac724ea0F3ed4fcb999bEe9af910fbe6;

        return $this;
    }

    /**
     * Gets a3e3b38588a54472B687879df649ca3e
     *
     * @return \Zitadel\Client\Model\UserServiceIDPIntent|null
     */
    public function getA3e3b38588a54472B687879df649ca3e()
    {
        return $this->container['a3e3b38588a54472B687879df649ca3e'];
    }

    /**
     * Sets a3e3b38588a54472B687879df649ca3e
     *
     * @param \Zitadel\Client\Model\UserServiceIDPIntent|null $a3e3b38588a54472B687879df649ca3e a3e3b38588a54472B687879df649ca3e
     *
     * @return self
     */
    public function setA3e3b38588a54472B687879df649ca3e($a3e3b38588a54472B687879df649ca3e)
    {
        if (is_null($a3e3b38588a54472B687879df649ca3e)) {
            throw new \InvalidArgumentException('non-nullable a3e3b38588a54472B687879df649ca3e cannot be null');
        }
        $this->container['a3e3b38588a54472B687879df649ca3e'] = $a3e3b38588a54472B687879df649ca3e;

        return $this;
    }

    /**
     * Gets _39c2a13153aa433492a0Ac7338b2ce67
     *
     * @return \Zitadel\Client\Model\UserServiceIDPLDAPAccessInformation|null
     */
    public function get39c2a13153aa433492a0Ac7338b2ce67()
    {
        return $this->container['_39c2a13153aa433492a0Ac7338b2ce67'];
    }

    /**
     * Sets _39c2a13153aa433492a0Ac7338b2ce67
     *
     * @param \Zitadel\Client\Model\UserServiceIDPLDAPAccessInformation|null $_39c2a13153aa433492a0Ac7338b2ce67 _39c2a13153aa433492a0Ac7338b2ce67
     *
     * @return self
     */
    public function set39c2a13153aa433492a0Ac7338b2ce67($_39c2a13153aa433492a0Ac7338b2ce67)
    {
        if (is_null($_39c2a13153aa433492a0Ac7338b2ce67)) {
            throw new \InvalidArgumentException('non-nullable _39c2a13153aa433492a0Ac7338b2ce67 cannot be null');
        }
        $this->container['_39c2a13153aa433492a0Ac7338b2ce67'] = $_39c2a13153aa433492a0Ac7338b2ce67;

        return $this;
    }

    /**
     * Gets b742b05fE9ca4dabA96628ac2d0da16c
     *
     * @return \Zitadel\Client\Model\UserServiceIDPOAuthAccessInformation|null
     */
    public function getB742b05fE9ca4dabA96628ac2d0da16c()
    {
        return $this->container['b742b05fE9ca4dabA96628ac2d0da16c'];
    }

    /**
     * Sets b742b05fE9ca4dabA96628ac2d0da16c
     *
     * @param \Zitadel\Client\Model\UserServiceIDPOAuthAccessInformation|null $b742b05fE9ca4dabA96628ac2d0da16c b742b05fE9ca4dabA96628ac2d0da16c
     *
     * @return self
     */
    public function setB742b05fE9ca4dabA96628ac2d0da16c($b742b05fE9ca4dabA96628ac2d0da16c)
    {
        if (is_null($b742b05fE9ca4dabA96628ac2d0da16c)) {
            throw new \InvalidArgumentException('non-nullable b742b05fE9ca4dabA96628ac2d0da16c cannot be null');
        }
        $this->container['b742b05fE9ca4dabA96628ac2d0da16c'] = $b742b05fE9ca4dabA96628ac2d0da16c;

        return $this;
    }

    /**
     * Gets _5098155e573f4c4885fe4f3c9c588931
     *
     * @return \Zitadel\Client\Model\UserServiceIDPSAMLAccessInformation|null
     */
    public function get5098155e573f4c4885fe4f3c9c588931()
    {
        return $this->container['_5098155e573f4c4885fe4f3c9c588931'];
    }

    /**
     * Sets _5098155e573f4c4885fe4f3c9c588931
     *
     * @param \Zitadel\Client\Model\UserServiceIDPSAMLAccessInformation|null $_5098155e573f4c4885fe4f3c9c588931 _5098155e573f4c4885fe4f3c9c588931
     *
     * @return self
     */
    public function set5098155e573f4c4885fe4f3c9c588931($_5098155e573f4c4885fe4f3c9c588931)
    {
        if (is_null($_5098155e573f4c4885fe4f3c9c588931)) {
            throw new \InvalidArgumentException('non-nullable _5098155e573f4c4885fe4f3c9c588931 cannot be null');
        }
        $this->container['_5098155e573f4c4885fe4f3c9c588931'] = $_5098155e573f4c4885fe4f3c9c588931;

        return $this;
    }

    /**
     * Gets _0e6081134718441e9482B82d45d55586
     *
     * @return \Zitadel\Client\Model\UserServiceInUserEmailsQuery|null
     */
    public function get0e6081134718441e9482B82d45d55586()
    {
        return $this->container['_0e6081134718441e9482B82d45d55586'];
    }

    /**
     * Sets _0e6081134718441e9482B82d45d55586
     *
     * @param \Zitadel\Client\Model\UserServiceInUserEmailsQuery|null $_0e6081134718441e9482B82d45d55586 _0e6081134718441e9482B82d45d55586
     *
     * @return self
     */
    public function set0e6081134718441e9482B82d45d55586($_0e6081134718441e9482B82d45d55586)
    {
        if (is_null($_0e6081134718441e9482B82d45d55586)) {
            throw new \InvalidArgumentException('non-nullable _0e6081134718441e9482B82d45d55586 cannot be null');
        }
        $this->container['_0e6081134718441e9482B82d45d55586'] = $_0e6081134718441e9482B82d45d55586;

        return $this;
    }

    /**
     * Gets b06ee9a421ac446eB16f9ee6703c52f2
     *
     * @return \Zitadel\Client\Model\UserServiceInUserIDQuery|null
     */
    public function getB06ee9a421ac446eB16f9ee6703c52f2()
    {
        return $this->container['b06ee9a421ac446eB16f9ee6703c52f2'];
    }

    /**
     * Sets b06ee9a421ac446eB16f9ee6703c52f2
     *
     * @param \Zitadel\Client\Model\UserServiceInUserIDQuery|null $b06ee9a421ac446eB16f9ee6703c52f2 b06ee9a421ac446eB16f9ee6703c52f2
     *
     * @return self
     */
    public function setB06ee9a421ac446eB16f9ee6703c52f2($b06ee9a421ac446eB16f9ee6703c52f2)
    {
        if (is_null($b06ee9a421ac446eB16f9ee6703c52f2)) {
            throw new \InvalidArgumentException('non-nullable b06ee9a421ac446eB16f9ee6703c52f2 cannot be null');
        }
        $this->container['b06ee9a421ac446eB16f9ee6703c52f2'] = $b06ee9a421ac446eB16f9ee6703c52f2;

        return $this;
    }

    /**
     * Gets c52030ba0a5d48bf8956396a28e6203b
     *
     * @return \Zitadel\Client\Model\UserServiceLDAPCredentials|null
     */
    public function getC52030ba0a5d48bf8956396a28e6203b()
    {
        return $this->container['c52030ba0a5d48bf8956396a28e6203b'];
    }

    /**
     * Sets c52030ba0a5d48bf8956396a28e6203b
     *
     * @param \Zitadel\Client\Model\UserServiceLDAPCredentials|null $c52030ba0a5d48bf8956396a28e6203b c52030ba0a5d48bf8956396a28e6203b
     *
     * @return self
     */
    public function setC52030ba0a5d48bf8956396a28e6203b($c52030ba0a5d48bf8956396a28e6203b)
    {
        if (is_null($c52030ba0a5d48bf8956396a28e6203b)) {
            throw new \InvalidArgumentException('non-nullable c52030ba0a5d48bf8956396a28e6203b cannot be null');
        }
        $this->container['c52030ba0a5d48bf8956396a28e6203b'] = $c52030ba0a5d48bf8956396a28e6203b;

        return $this;
    }

    /**
     * Gets _93616c1c65564f8d9446Aa25ddb024fd
     *
     * @return \Zitadel\Client\Model\UserServiceLastNameQuery|null
     */
    public function get93616c1c65564f8d9446Aa25ddb024fd()
    {
        return $this->container['_93616c1c65564f8d9446Aa25ddb024fd'];
    }

    /**
     * Sets _93616c1c65564f8d9446Aa25ddb024fd
     *
     * @param \Zitadel\Client\Model\UserServiceLastNameQuery|null $_93616c1c65564f8d9446Aa25ddb024fd _93616c1c65564f8d9446Aa25ddb024fd
     *
     * @return self
     */
    public function set93616c1c65564f8d9446Aa25ddb024fd($_93616c1c65564f8d9446Aa25ddb024fd)
    {
        if (is_null($_93616c1c65564f8d9446Aa25ddb024fd)) {
            throw new \InvalidArgumentException('non-nullable _93616c1c65564f8d9446Aa25ddb024fd cannot be null');
        }
        $this->container['_93616c1c65564f8d9446Aa25ddb024fd'] = $_93616c1c65564f8d9446Aa25ddb024fd;

        return $this;
    }

    /**
     * Gets _73c97b6fEcbc46d9B33aC76b0193fa24
     *
     * @return \Zitadel\Client\Model\UserServiceLoginNameQuery|null
     */
    public function get73c97b6fEcbc46d9B33aC76b0193fa24()
    {
        return $this->container['_73c97b6fEcbc46d9B33aC76b0193fa24'];
    }

    /**
     * Sets _73c97b6fEcbc46d9B33aC76b0193fa24
     *
     * @param \Zitadel\Client\Model\UserServiceLoginNameQuery|null $_73c97b6fEcbc46d9B33aC76b0193fa24 _73c97b6fEcbc46d9B33aC76b0193fa24
     *
     * @return self
     */
    public function set73c97b6fEcbc46d9B33aC76b0193fa24($_73c97b6fEcbc46d9B33aC76b0193fa24)
    {
        if (is_null($_73c97b6fEcbc46d9B33aC76b0193fa24)) {
            throw new \InvalidArgumentException('non-nullable _73c97b6fEcbc46d9B33aC76b0193fa24 cannot be null');
        }
        $this->container['_73c97b6fEcbc46d9B33aC76b0193fa24'] = $_73c97b6fEcbc46d9B33aC76b0193fa24;

        return $this;
    }

    /**
     * Gets _9237e11bE85948c799d837be608b578f
     *
     * @return \Zitadel\Client\Model\UserServiceMachineUser|null
     */
    public function get9237e11bE85948c799d837be608b578f()
    {
        return $this->container['_9237e11bE85948c799d837be608b578f'];
    }

    /**
     * Sets _9237e11bE85948c799d837be608b578f
     *
     * @param \Zitadel\Client\Model\UserServiceMachineUser|null $_9237e11bE85948c799d837be608b578f _9237e11bE85948c799d837be608b578f
     *
     * @return self
     */
    public function set9237e11bE85948c799d837be608b578f($_9237e11bE85948c799d837be608b578f)
    {
        if (is_null($_9237e11bE85948c799d837be608b578f)) {
            throw new \InvalidArgumentException('non-nullable _9237e11bE85948c799d837be608b578f cannot be null');
        }
        $this->container['_9237e11bE85948c799d837be608b578f'] = $_9237e11bE85948c799d837be608b578f;

        return $this;
    }

    /**
     * Gets _41ea4efa714b49a0B7a45ea0accb986d
     *
     * @return \Zitadel\Client\Model\UserServiceNickNameQuery|null
     */
    public function get41ea4efa714b49a0B7a45ea0accb986d()
    {
        return $this->container['_41ea4efa714b49a0B7a45ea0accb986d'];
    }

    /**
     * Sets _41ea4efa714b49a0B7a45ea0accb986d
     *
     * @param \Zitadel\Client\Model\UserServiceNickNameQuery|null $_41ea4efa714b49a0B7a45ea0accb986d _41ea4efa714b49a0B7a45ea0accb986d
     *
     * @return self
     */
    public function set41ea4efa714b49a0B7a45ea0accb986d($_41ea4efa714b49a0B7a45ea0accb986d)
    {
        if (is_null($_41ea4efa714b49a0B7a45ea0accb986d)) {
            throw new \InvalidArgumentException('non-nullable _41ea4efa714b49a0B7a45ea0accb986d cannot be null');
        }
        $this->container['_41ea4efa714b49a0B7a45ea0accb986d'] = $_41ea4efa714b49a0B7a45ea0accb986d;

        return $this;
    }

    /**
     * Gets a614946e6bd04b26B9474d18205eda35
     *
     * @return \Zitadel\Client\Model\UserServiceNotQuery|null
     */
    public function getA614946e6bd04b26B9474d18205eda35()
    {
        return $this->container['a614946e6bd04b26B9474d18205eda35'];
    }

    /**
     * Sets a614946e6bd04b26B9474d18205eda35
     *
     * @param \Zitadel\Client\Model\UserServiceNotQuery|null $a614946e6bd04b26B9474d18205eda35 a614946e6bd04b26B9474d18205eda35
     *
     * @return self
     */
    public function setA614946e6bd04b26B9474d18205eda35($a614946e6bd04b26B9474d18205eda35)
    {
        if (is_null($a614946e6bd04b26B9474d18205eda35)) {
            throw new \InvalidArgumentException('non-nullable a614946e6bd04b26B9474d18205eda35 cannot be null');
        }
        $this->container['a614946e6bd04b26B9474d18205eda35'] = $a614946e6bd04b26B9474d18205eda35;

        return $this;
    }

    /**
     * Gets _652fb458324344c1B75a9dcf0b130c7b
     *
     * @return \Zitadel\Client\Model\UserServiceOrQuery|null
     */
    public function get652fb458324344c1B75a9dcf0b130c7b()
    {
        return $this->container['_652fb458324344c1B75a9dcf0b130c7b'];
    }

    /**
     * Sets _652fb458324344c1B75a9dcf0b130c7b
     *
     * @param \Zitadel\Client\Model\UserServiceOrQuery|null $_652fb458324344c1B75a9dcf0b130c7b _652fb458324344c1B75a9dcf0b130c7b
     *
     * @return self
     */
    public function set652fb458324344c1B75a9dcf0b130c7b($_652fb458324344c1B75a9dcf0b130c7b)
    {
        if (is_null($_652fb458324344c1B75a9dcf0b130c7b)) {
            throw new \InvalidArgumentException('non-nullable _652fb458324344c1B75a9dcf0b130c7b cannot be null');
        }
        $this->container['_652fb458324344c1B75a9dcf0b130c7b'] = $_652fb458324344c1B75a9dcf0b130c7b;

        return $this;
    }

    /**
     * Gets _0063cccdE3f74f838a9fF9f2f2001fa9
     *
     * @return \Zitadel\Client\Model\UserServiceOrganizationIdQuery|null
     */
    public function get0063cccdE3f74f838a9fF9f2f2001fa9()
    {
        return $this->container['_0063cccdE3f74f838a9fF9f2f2001fa9'];
    }

    /**
     * Sets _0063cccdE3f74f838a9fF9f2f2001fa9
     *
     * @param \Zitadel\Client\Model\UserServiceOrganizationIdQuery|null $_0063cccdE3f74f838a9fF9f2f2001fa9 _0063cccdE3f74f838a9fF9f2f2001fa9
     *
     * @return self
     */
    public function set0063cccdE3f74f838a9fF9f2f2001fa9($_0063cccdE3f74f838a9fF9f2f2001fa9)
    {
        if (is_null($_0063cccdE3f74f838a9fF9f2f2001fa9)) {
            throw new \InvalidArgumentException('non-nullable _0063cccdE3f74f838a9fF9f2f2001fa9 cannot be null');
        }
        $this->container['_0063cccdE3f74f838a9fF9f2f2001fa9'] = $_0063cccdE3f74f838a9fF9f2f2001fa9;

        return $this;
    }

    /**
     * Gets _5340fb08D5454c8cB47aEcb6bfaa621a
     *
     * @return \Zitadel\Client\Model\UserServicePassword|null
     */
    public function get5340fb08D5454c8cB47aEcb6bfaa621a()
    {
        return $this->container['_5340fb08D5454c8cB47aEcb6bfaa621a'];
    }

    /**
     * Sets _5340fb08D5454c8cB47aEcb6bfaa621a
     *
     * @param \Zitadel\Client\Model\UserServicePassword|null $_5340fb08D5454c8cB47aEcb6bfaa621a _5340fb08D5454c8cB47aEcb6bfaa621a
     *
     * @return self
     */
    public function set5340fb08D5454c8cB47aEcb6bfaa621a($_5340fb08D5454c8cB47aEcb6bfaa621a)
    {
        if (is_null($_5340fb08D5454c8cB47aEcb6bfaa621a)) {
            throw new \InvalidArgumentException('non-nullable _5340fb08D5454c8cB47aEcb6bfaa621a cannot be null');
        }
        $this->container['_5340fb08D5454c8cB47aEcb6bfaa621a'] = $_5340fb08D5454c8cB47aEcb6bfaa621a;

        return $this;
    }

    /**
     * Gets ed2e8b696e674202A1b0Ecfd937d2ddf
     *
     * @return \Zitadel\Client\Model\UserServicePhoneQuery|null
     */
    public function getEd2e8b696e674202A1b0Ecfd937d2ddf()
    {
        return $this->container['ed2e8b696e674202A1b0Ecfd937d2ddf'];
    }

    /**
     * Sets ed2e8b696e674202A1b0Ecfd937d2ddf
     *
     * @param \Zitadel\Client\Model\UserServicePhoneQuery|null $ed2e8b696e674202A1b0Ecfd937d2ddf ed2e8b696e674202A1b0Ecfd937d2ddf
     *
     * @return self
     */
    public function setEd2e8b696e674202A1b0Ecfd937d2ddf($ed2e8b696e674202A1b0Ecfd937d2ddf)
    {
        if (is_null($ed2e8b696e674202A1b0Ecfd937d2ddf)) {
            throw new \InvalidArgumentException('non-nullable ed2e8b696e674202A1b0Ecfd937d2ddf cannot be null');
        }
        $this->container['ed2e8b696e674202A1b0Ecfd937d2ddf'] = $ed2e8b696e674202A1b0Ecfd937d2ddf;

        return $this;
    }

    /**
     * Gets _9e93d1822acf4856A9166e0d81d39cea
     *
     * @return \Zitadel\Client\Model\UserServiceRedirectURLs|null
     */
    public function get9e93d1822acf4856A9166e0d81d39cea()
    {
        return $this->container['_9e93d1822acf4856A9166e0d81d39cea'];
    }

    /**
     * Sets _9e93d1822acf4856A9166e0d81d39cea
     *
     * @param \Zitadel\Client\Model\UserServiceRedirectURLs|null $_9e93d1822acf4856A9166e0d81d39cea _9e93d1822acf4856A9166e0d81d39cea
     *
     * @return self
     */
    public function set9e93d1822acf4856A9166e0d81d39cea($_9e93d1822acf4856A9166e0d81d39cea)
    {
        if (is_null($_9e93d1822acf4856A9166e0d81d39cea)) {
            throw new \InvalidArgumentException('non-nullable _9e93d1822acf4856A9166e0d81d39cea cannot be null');
        }
        $this->container['_9e93d1822acf4856A9166e0d81d39cea'] = $_9e93d1822acf4856A9166e0d81d39cea;

        return $this;
    }

    /**
     * Gets _1fc91c19Eef245c885146c624f785660
     *
     * @return object|null
     */
    public function get1fc91c19Eef245c885146c624f785660()
    {
        return $this->container['_1fc91c19Eef245c885146c624f785660'];
    }

    /**
     * Sets _1fc91c19Eef245c885146c624f785660
     *
     * @param object|null $_1fc91c19Eef245c885146c624f785660 _1fc91c19Eef245c885146c624f785660
     *
     * @return self
     */
    public function set1fc91c19Eef245c885146c624f785660($_1fc91c19Eef245c885146c624f785660)
    {
        if (is_null($_1fc91c19Eef245c885146c624f785660)) {
            throw new \InvalidArgumentException('non-nullable _1fc91c19Eef245c885146c624f785660 cannot be null');
        }
        $this->container['_1fc91c19Eef245c885146c624f785660'] = $_1fc91c19Eef245c885146c624f785660;

        return $this;
    }

    /**
     * Gets c13ba8a142834a8c9291126631d1ad41
     *
     * @return object|null
     */
    public function getC13ba8a142834a8c9291126631d1ad41()
    {
        return $this->container['c13ba8a142834a8c9291126631d1ad41'];
    }

    /**
     * Sets c13ba8a142834a8c9291126631d1ad41
     *
     * @param object|null $c13ba8a142834a8c9291126631d1ad41 c13ba8a142834a8c9291126631d1ad41
     *
     * @return self
     */
    public function setC13ba8a142834a8c9291126631d1ad41($c13ba8a142834a8c9291126631d1ad41)
    {
        if (is_null($c13ba8a142834a8c9291126631d1ad41)) {
            throw new \InvalidArgumentException('non-nullable c13ba8a142834a8c9291126631d1ad41 cannot be null');
        }
        $this->container['c13ba8a142834a8c9291126631d1ad41'] = $c13ba8a142834a8c9291126631d1ad41;

        return $this;
    }

    /**
     * Gets _3e19c9726f3f4eb68ca296cd9f2087ea
     *
     * @return object|null
     */
    public function get3e19c9726f3f4eb68ca296cd9f2087ea()
    {
        return $this->container['_3e19c9726f3f4eb68ca296cd9f2087ea'];
    }

    /**
     * Sets _3e19c9726f3f4eb68ca296cd9f2087ea
     *
     * @param object|null $_3e19c9726f3f4eb68ca296cd9f2087ea _3e19c9726f3f4eb68ca296cd9f2087ea
     *
     * @return self
     */
    public function set3e19c9726f3f4eb68ca296cd9f2087ea($_3e19c9726f3f4eb68ca296cd9f2087ea)
    {
        if (is_null($_3e19c9726f3f4eb68ca296cd9f2087ea)) {
            throw new \InvalidArgumentException('non-nullable _3e19c9726f3f4eb68ca296cd9f2087ea cannot be null');
        }
        $this->container['_3e19c9726f3f4eb68ca296cd9f2087ea'] = $_3e19c9726f3f4eb68ca296cd9f2087ea;

        return $this;
    }

    /**
     * Gets _74045de494c84118B0a2E40a23bf4399
     *
     * @return object|null
     */
    public function get74045de494c84118B0a2E40a23bf4399()
    {
        return $this->container['_74045de494c84118B0a2E40a23bf4399'];
    }

    /**
     * Sets _74045de494c84118B0a2E40a23bf4399
     *
     * @param object|null $_74045de494c84118B0a2E40a23bf4399 _74045de494c84118B0a2E40a23bf4399
     *
     * @return self
     */
    public function set74045de494c84118B0a2E40a23bf4399($_74045de494c84118B0a2E40a23bf4399)
    {
        if (is_null($_74045de494c84118B0a2E40a23bf4399)) {
            throw new \InvalidArgumentException('non-nullable _74045de494c84118B0a2E40a23bf4399 cannot be null');
        }
        $this->container['_74045de494c84118B0a2E40a23bf4399'] = $_74045de494c84118B0a2E40a23bf4399;

        return $this;
    }

    /**
     * Gets f2f1dabe90ec4e66Bb06308dda585c74
     *
     * @return object|null
     */
    public function getF2f1dabe90ec4e66Bb06308dda585c74()
    {
        return $this->container['f2f1dabe90ec4e66Bb06308dda585c74'];
    }

    /**
     * Sets f2f1dabe90ec4e66Bb06308dda585c74
     *
     * @param object|null $f2f1dabe90ec4e66Bb06308dda585c74 f2f1dabe90ec4e66Bb06308dda585c74
     *
     * @return self
     */
    public function setF2f1dabe90ec4e66Bb06308dda585c74($f2f1dabe90ec4e66Bb06308dda585c74)
    {
        if (is_null($f2f1dabe90ec4e66Bb06308dda585c74)) {
            throw new \InvalidArgumentException('non-nullable f2f1dabe90ec4e66Bb06308dda585c74 cannot be null');
        }
        $this->container['f2f1dabe90ec4e66Bb06308dda585c74'] = $f2f1dabe90ec4e66Bb06308dda585c74;

        return $this;
    }

    /**
     * Gets _98d4b310Bd3a4be3954e393580550f8e
     *
     * @return \Zitadel\Client\Model\UserServiceSendEmailVerificationCode|null
     */
    public function get98d4b310Bd3a4be3954e393580550f8e()
    {
        return $this->container['_98d4b310Bd3a4be3954e393580550f8e'];
    }

    /**
     * Sets _98d4b310Bd3a4be3954e393580550f8e
     *
     * @param \Zitadel\Client\Model\UserServiceSendEmailVerificationCode|null $_98d4b310Bd3a4be3954e393580550f8e _98d4b310Bd3a4be3954e393580550f8e
     *
     * @return self
     */
    public function set98d4b310Bd3a4be3954e393580550f8e($_98d4b310Bd3a4be3954e393580550f8e)
    {
        if (is_null($_98d4b310Bd3a4be3954e393580550f8e)) {
            throw new \InvalidArgumentException('non-nullable _98d4b310Bd3a4be3954e393580550f8e cannot be null');
        }
        $this->container['_98d4b310Bd3a4be3954e393580550f8e'] = $_98d4b310Bd3a4be3954e393580550f8e;

        return $this;
    }

    /**
     * Gets _9dd39bba3a0747329fbaB304fd0e5a88
     *
     * @return \Zitadel\Client\Model\UserServiceSendInviteCode|null
     */
    public function get9dd39bba3a0747329fbaB304fd0e5a88()
    {
        return $this->container['_9dd39bba3a0747329fbaB304fd0e5a88'];
    }

    /**
     * Sets _9dd39bba3a0747329fbaB304fd0e5a88
     *
     * @param \Zitadel\Client\Model\UserServiceSendInviteCode|null $_9dd39bba3a0747329fbaB304fd0e5a88 _9dd39bba3a0747329fbaB304fd0e5a88
     *
     * @return self
     */
    public function set9dd39bba3a0747329fbaB304fd0e5a88($_9dd39bba3a0747329fbaB304fd0e5a88)
    {
        if (is_null($_9dd39bba3a0747329fbaB304fd0e5a88)) {
            throw new \InvalidArgumentException('non-nullable _9dd39bba3a0747329fbaB304fd0e5a88 cannot be null');
        }
        $this->container['_9dd39bba3a0747329fbaB304fd0e5a88'] = $_9dd39bba3a0747329fbaB304fd0e5a88;

        return $this;
    }

    /**
     * Gets _236b67a626aa4cf79c3dF15e31eef06b
     *
     * @return \Zitadel\Client\Model\UserServiceSendPasskeyRegistrationLink|null
     */
    public function get236b67a626aa4cf79c3dF15e31eef06b()
    {
        return $this->container['_236b67a626aa4cf79c3dF15e31eef06b'];
    }

    /**
     * Sets _236b67a626aa4cf79c3dF15e31eef06b
     *
     * @param \Zitadel\Client\Model\UserServiceSendPasskeyRegistrationLink|null $_236b67a626aa4cf79c3dF15e31eef06b _236b67a626aa4cf79c3dF15e31eef06b
     *
     * @return self
     */
    public function set236b67a626aa4cf79c3dF15e31eef06b($_236b67a626aa4cf79c3dF15e31eef06b)
    {
        if (is_null($_236b67a626aa4cf79c3dF15e31eef06b)) {
            throw new \InvalidArgumentException('non-nullable _236b67a626aa4cf79c3dF15e31eef06b cannot be null');
        }
        $this->container['_236b67a626aa4cf79c3dF15e31eef06b'] = $_236b67a626aa4cf79c3dF15e31eef06b;

        return $this;
    }

    /**
     * Gets _8a890a58C2fc478486de6d34c866bc6d
     *
     * @return \Zitadel\Client\Model\UserServiceSendPasswordResetLink|null
     */
    public function get8a890a58C2fc478486de6d34c866bc6d()
    {
        return $this->container['_8a890a58C2fc478486de6d34c866bc6d'];
    }

    /**
     * Sets _8a890a58C2fc478486de6d34c866bc6d
     *
     * @param \Zitadel\Client\Model\UserServiceSendPasswordResetLink|null $_8a890a58C2fc478486de6d34c866bc6d _8a890a58C2fc478486de6d34c866bc6d
     *
     * @return self
     */
    public function set8a890a58C2fc478486de6d34c866bc6d($_8a890a58C2fc478486de6d34c866bc6d)
    {
        if (is_null($_8a890a58C2fc478486de6d34c866bc6d)) {
            throw new \InvalidArgumentException('non-nullable _8a890a58C2fc478486de6d34c866bc6d cannot be null');
        }
        $this->container['_8a890a58C2fc478486de6d34c866bc6d'] = $_8a890a58C2fc478486de6d34c866bc6d;

        return $this;
    }

    /**
     * Gets _80a2ea0167c94c08A15d8aa8c5f65814
     *
     * @return object|null
     */
    public function get80a2ea0167c94c08A15d8aa8c5f65814()
    {
        return $this->container['_80a2ea0167c94c08A15d8aa8c5f65814'];
    }

    /**
     * Sets _80a2ea0167c94c08A15d8aa8c5f65814
     *
     * @param object|null $_80a2ea0167c94c08A15d8aa8c5f65814 _80a2ea0167c94c08A15d8aa8c5f65814
     *
     * @return self
     */
    public function set80a2ea0167c94c08A15d8aa8c5f65814($_80a2ea0167c94c08A15d8aa8c5f65814)
    {
        if (is_null($_80a2ea0167c94c08A15d8aa8c5f65814)) {
            throw new \InvalidArgumentException('non-nullable _80a2ea0167c94c08A15d8aa8c5f65814 cannot be null');
        }
        $this->container['_80a2ea0167c94c08A15d8aa8c5f65814'] = $_80a2ea0167c94c08A15d8aa8c5f65814;

        return $this;
    }

    /**
     * Gets fb1210fc309744c9AdfeB5f65ae80aad
     *
     * @return \Zitadel\Client\Model\UserServiceStateQuery|null
     */
    public function getFb1210fc309744c9AdfeB5f65ae80aad()
    {
        return $this->container['fb1210fc309744c9AdfeB5f65ae80aad'];
    }

    /**
     * Sets fb1210fc309744c9AdfeB5f65ae80aad
     *
     * @param \Zitadel\Client\Model\UserServiceStateQuery|null $fb1210fc309744c9AdfeB5f65ae80aad fb1210fc309744c9AdfeB5f65ae80aad
     *
     * @return self
     */
    public function setFb1210fc309744c9AdfeB5f65ae80aad($fb1210fc309744c9AdfeB5f65ae80aad)
    {
        if (is_null($fb1210fc309744c9AdfeB5f65ae80aad)) {
            throw new \InvalidArgumentException('non-nullable fb1210fc309744c9AdfeB5f65ae80aad cannot be null');
        }
        $this->container['fb1210fc309744c9AdfeB5f65ae80aad'] = $fb1210fc309744c9AdfeB5f65ae80aad;

        return $this;
    }

    /**
     * Gets _5453af57519541e1A89a815aefafd209
     *
     * @return \Zitadel\Client\Model\UserServiceTypeQuery|null
     */
    public function get5453af57519541e1A89a815aefafd209()
    {
        return $this->container['_5453af57519541e1A89a815aefafd209'];
    }

    /**
     * Sets _5453af57519541e1A89a815aefafd209
     *
     * @param \Zitadel\Client\Model\UserServiceTypeQuery|null $_5453af57519541e1A89a815aefafd209 _5453af57519541e1A89a815aefafd209
     *
     * @return self
     */
    public function set5453af57519541e1A89a815aefafd209($_5453af57519541e1A89a815aefafd209)
    {
        if (is_null($_5453af57519541e1A89a815aefafd209)) {
            throw new \InvalidArgumentException('non-nullable _5453af57519541e1A89a815aefafd209 cannot be null');
        }
        $this->container['_5453af57519541e1A89a815aefafd209'] = $_5453af57519541e1A89a815aefafd209;

        return $this;
    }

    /**
     * Gets ffb17b46E3dc4eaaB8fe611e1ace506d
     *
     * @return \Zitadel\Client\Model\UserServiceUserNameQuery|null
     */
    public function getFfb17b46E3dc4eaaB8fe611e1ace506d()
    {
        return $this->container['ffb17b46E3dc4eaaB8fe611e1ace506d'];
    }

    /**
     * Sets ffb17b46E3dc4eaaB8fe611e1ace506d
     *
     * @param \Zitadel\Client\Model\UserServiceUserNameQuery|null $ffb17b46E3dc4eaaB8fe611e1ace506d ffb17b46E3dc4eaaB8fe611e1ace506d
     *
     * @return self
     */
    public function setFfb17b46E3dc4eaaB8fe611e1ace506d($ffb17b46E3dc4eaaB8fe611e1ace506d)
    {
        if (is_null($ffb17b46E3dc4eaaB8fe611e1ace506d)) {
            throw new \InvalidArgumentException('non-nullable ffb17b46E3dc4eaaB8fe611e1ace506d cannot be null');
        }
        $this->container['ffb17b46E3dc4eaaB8fe611e1ace506d'] = $ffb17b46E3dc4eaaB8fe611e1ace506d;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


