<?php
/**
 * NoOp200Response8
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zitadel SDK
 *
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;

use \ArrayAccess;
use \Zitadel\Client\ObjectSerializer;

/**
 * NoOp200Response8 Class Doc Comment
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoOp200Response8 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoOp_200_response_8';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'c95cf2efB5714870B3672e2a7baac12b' => '\Zitadel\Client\Model\OIDCServiceAuthorizationError',
        '_5d818299Ec8d469cB12cD427e9b5ce14' => 'object',
        '_6972f48986044af4Add8A032f9b171f4' => '\Zitadel\Client\Model\OIDCServiceSession'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'c95cf2efB5714870B3672e2a7baac12b' => null,
        '_5d818299Ec8d469cB12cD427e9b5ce14' => null,
        '_6972f48986044af4Add8A032f9b171f4' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'c95cf2efB5714870B3672e2a7baac12b' => false,
        '_5d818299Ec8d469cB12cD427e9b5ce14' => false,
        '_6972f48986044af4Add8A032f9b171f4' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'c95cf2efB5714870B3672e2a7baac12b' => 'c95cf2ef-b571-4870-b367-2e2a7baac12b',
        '_5d818299Ec8d469cB12cD427e9b5ce14' => '5d818299-ec8d-469c-b12c-d427e9b5ce14',
        '_6972f48986044af4Add8A032f9b171f4' => '6972f489-8604-4af4-add8-a032f9b171f4'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'c95cf2efB5714870B3672e2a7baac12b' => 'setC95cf2efB5714870B3672e2a7baac12b',
        '_5d818299Ec8d469cB12cD427e9b5ce14' => 'set5d818299Ec8d469cB12cD427e9b5ce14',
        '_6972f48986044af4Add8A032f9b171f4' => 'set6972f48986044af4Add8A032f9b171f4'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'c95cf2efB5714870B3672e2a7baac12b' => 'getC95cf2efB5714870B3672e2a7baac12b',
        '_5d818299Ec8d469cB12cD427e9b5ce14' => 'get5d818299Ec8d469cB12cD427e9b5ce14',
        '_6972f48986044af4Add8A032f9b171f4' => 'get6972f48986044af4Add8A032f9b171f4'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('c95cf2efB5714870B3672e2a7baac12b', $data ?? [], null);
        $this->setIfExists('_5d818299Ec8d469cB12cD427e9b5ce14', $data ?? [], null);
        $this->setIfExists('_6972f48986044af4Add8A032f9b171f4', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets c95cf2efB5714870B3672e2a7baac12b
     *
     * @return \Zitadel\Client\Model\OIDCServiceAuthorizationError|null
     */
    public function getC95cf2efB5714870B3672e2a7baac12b()
    {
        return $this->container['c95cf2efB5714870B3672e2a7baac12b'];
    }

    /**
     * Sets c95cf2efB5714870B3672e2a7baac12b
     *
     * @param \Zitadel\Client\Model\OIDCServiceAuthorizationError|null $c95cf2efB5714870B3672e2a7baac12b c95cf2efB5714870B3672e2a7baac12b
     *
     * @return self
     */
    public function setC95cf2efB5714870B3672e2a7baac12b($c95cf2efB5714870B3672e2a7baac12b)
    {
        if (is_null($c95cf2efB5714870B3672e2a7baac12b)) {
            throw new \InvalidArgumentException('non-nullable c95cf2efB5714870B3672e2a7baac12b cannot be null');
        }
        $this->container['c95cf2efB5714870B3672e2a7baac12b'] = $c95cf2efB5714870B3672e2a7baac12b;

        return $this;
    }

    /**
     * Gets _5d818299Ec8d469cB12cD427e9b5ce14
     *
     * @return object|null
     */
    public function get5d818299Ec8d469cB12cD427e9b5ce14()
    {
        return $this->container['_5d818299Ec8d469cB12cD427e9b5ce14'];
    }

    /**
     * Sets _5d818299Ec8d469cB12cD427e9b5ce14
     *
     * @param object|null $_5d818299Ec8d469cB12cD427e9b5ce14 _5d818299Ec8d469cB12cD427e9b5ce14
     *
     * @return self
     */
    public function set5d818299Ec8d469cB12cD427e9b5ce14($_5d818299Ec8d469cB12cD427e9b5ce14)
    {
        if (is_null($_5d818299Ec8d469cB12cD427e9b5ce14)) {
            throw new \InvalidArgumentException('non-nullable _5d818299Ec8d469cB12cD427e9b5ce14 cannot be null');
        }
        $this->container['_5d818299Ec8d469cB12cD427e9b5ce14'] = $_5d818299Ec8d469cB12cD427e9b5ce14;

        return $this;
    }

    /**
     * Gets _6972f48986044af4Add8A032f9b171f4
     *
     * @return \Zitadel\Client\Model\OIDCServiceSession|null
     */
    public function get6972f48986044af4Add8A032f9b171f4()
    {
        return $this->container['_6972f48986044af4Add8A032f9b171f4'];
    }

    /**
     * Sets _6972f48986044af4Add8A032f9b171f4
     *
     * @param \Zitadel\Client\Model\OIDCServiceSession|null $_6972f48986044af4Add8A032f9b171f4 _6972f48986044af4Add8A032f9b171f4
     *
     * @return self
     */
    public function set6972f48986044af4Add8A032f9b171f4($_6972f48986044af4Add8A032f9b171f4)
    {
        if (is_null($_6972f48986044af4Add8A032f9b171f4)) {
            throw new \InvalidArgumentException('non-nullable _6972f48986044af4Add8A032f9b171f4 cannot be null');
        }
        $this->container['_6972f48986044af4Add8A032f9b171f4'] = $_6972f48986044af4Add8A032f9b171f4;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


