<?php
/**
 * NoOp200Response4
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zitadel SDK
 *
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;

use \ArrayAccess;
use \Zitadel\Client\ObjectSerializer;

/**
 * NoOp200Response4 Class Doc Comment
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NoOp200Response4 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NoOp_200_response_4';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        '_92efaf3f183d4dabB2f6B56cb5a0264b' => '\Zitadel\Client\Model\SessionServiceCreationDateQuery',
        '_92e1aabb9f9642a6B430Edb9f29dbf96' => '\Zitadel\Client\Model\SessionServiceCreatorQuery',
        '_083493f65d72451383fb9d5f178945a7' => '\Zitadel\Client\Model\SessionServiceIDsQuery',
        '_38908444a5bf47a382972b1943eef4db' => 'object',
        'b2b79f3503fb473aBaf9E458501ff7cd' => '\Zitadel\Client\Model\SessionServiceSendCode',
        '_525266101d1d4f478dfc33cd53a38165' => '\Zitadel\Client\Model\SessionServiceUserAgentQuery',
        '_35b955a40ab54075864d72eadf73bb86' => '\Zitadel\Client\Model\SessionServiceUserIDQuery'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        '_92efaf3f183d4dabB2f6B56cb5a0264b' => null,
        '_92e1aabb9f9642a6B430Edb9f29dbf96' => null,
        '_083493f65d72451383fb9d5f178945a7' => null,
        '_38908444a5bf47a382972b1943eef4db' => null,
        'b2b79f3503fb473aBaf9E458501ff7cd' => null,
        '_525266101d1d4f478dfc33cd53a38165' => null,
        '_35b955a40ab54075864d72eadf73bb86' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        '_92efaf3f183d4dabB2f6B56cb5a0264b' => false,
        '_92e1aabb9f9642a6B430Edb9f29dbf96' => false,
        '_083493f65d72451383fb9d5f178945a7' => false,
        '_38908444a5bf47a382972b1943eef4db' => false,
        'b2b79f3503fb473aBaf9E458501ff7cd' => false,
        '_525266101d1d4f478dfc33cd53a38165' => false,
        '_35b955a40ab54075864d72eadf73bb86' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_92efaf3f183d4dabB2f6B56cb5a0264b' => '92efaf3f-183d-4dab-b2f6-b56cb5a0264b',
        '_92e1aabb9f9642a6B430Edb9f29dbf96' => '92e1aabb-9f96-42a6-b430-edb9f29dbf96',
        '_083493f65d72451383fb9d5f178945a7' => '083493f6-5d72-4513-83fb-9d5f178945a7',
        '_38908444a5bf47a382972b1943eef4db' => '38908444-a5bf-47a3-8297-2b1943eef4db',
        'b2b79f3503fb473aBaf9E458501ff7cd' => 'b2b79f35-03fb-473a-baf9-e458501ff7cd',
        '_525266101d1d4f478dfc33cd53a38165' => '52526610-1d1d-4f47-8dfc-33cd53a38165',
        '_35b955a40ab54075864d72eadf73bb86' => '35b955a4-0ab5-4075-864d-72eadf73bb86'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_92efaf3f183d4dabB2f6B56cb5a0264b' => 'set92efaf3f183d4dabB2f6B56cb5a0264b',
        '_92e1aabb9f9642a6B430Edb9f29dbf96' => 'set92e1aabb9f9642a6B430Edb9f29dbf96',
        '_083493f65d72451383fb9d5f178945a7' => 'set083493f65d72451383fb9d5f178945a7',
        '_38908444a5bf47a382972b1943eef4db' => 'set38908444a5bf47a382972b1943eef4db',
        'b2b79f3503fb473aBaf9E458501ff7cd' => 'setB2b79f3503fb473aBaf9E458501ff7cd',
        '_525266101d1d4f478dfc33cd53a38165' => 'set525266101d1d4f478dfc33cd53a38165',
        '_35b955a40ab54075864d72eadf73bb86' => 'set35b955a40ab54075864d72eadf73bb86'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_92efaf3f183d4dabB2f6B56cb5a0264b' => 'get92efaf3f183d4dabB2f6B56cb5a0264b',
        '_92e1aabb9f9642a6B430Edb9f29dbf96' => 'get92e1aabb9f9642a6B430Edb9f29dbf96',
        '_083493f65d72451383fb9d5f178945a7' => 'get083493f65d72451383fb9d5f178945a7',
        '_38908444a5bf47a382972b1943eef4db' => 'get38908444a5bf47a382972b1943eef4db',
        'b2b79f3503fb473aBaf9E458501ff7cd' => 'getB2b79f3503fb473aBaf9E458501ff7cd',
        '_525266101d1d4f478dfc33cd53a38165' => 'get525266101d1d4f478dfc33cd53a38165',
        '_35b955a40ab54075864d72eadf73bb86' => 'get35b955a40ab54075864d72eadf73bb86'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('_92efaf3f183d4dabB2f6B56cb5a0264b', $data ?? [], null);
        $this->setIfExists('_92e1aabb9f9642a6B430Edb9f29dbf96', $data ?? [], null);
        $this->setIfExists('_083493f65d72451383fb9d5f178945a7', $data ?? [], null);
        $this->setIfExists('_38908444a5bf47a382972b1943eef4db', $data ?? [], null);
        $this->setIfExists('b2b79f3503fb473aBaf9E458501ff7cd', $data ?? [], null);
        $this->setIfExists('_525266101d1d4f478dfc33cd53a38165', $data ?? [], null);
        $this->setIfExists('_35b955a40ab54075864d72eadf73bb86', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _92efaf3f183d4dabB2f6B56cb5a0264b
     *
     * @return \Zitadel\Client\Model\SessionServiceCreationDateQuery|null
     */
    public function get92efaf3f183d4dabB2f6B56cb5a0264b()
    {
        return $this->container['_92efaf3f183d4dabB2f6B56cb5a0264b'];
    }

    /**
     * Sets _92efaf3f183d4dabB2f6B56cb5a0264b
     *
     * @param \Zitadel\Client\Model\SessionServiceCreationDateQuery|null $_92efaf3f183d4dabB2f6B56cb5a0264b _92efaf3f183d4dabB2f6B56cb5a0264b
     *
     * @return self
     */
    public function set92efaf3f183d4dabB2f6B56cb5a0264b($_92efaf3f183d4dabB2f6B56cb5a0264b)
    {
        if (is_null($_92efaf3f183d4dabB2f6B56cb5a0264b)) {
            throw new \InvalidArgumentException('non-nullable _92efaf3f183d4dabB2f6B56cb5a0264b cannot be null');
        }
        $this->container['_92efaf3f183d4dabB2f6B56cb5a0264b'] = $_92efaf3f183d4dabB2f6B56cb5a0264b;

        return $this;
    }

    /**
     * Gets _92e1aabb9f9642a6B430Edb9f29dbf96
     *
     * @return \Zitadel\Client\Model\SessionServiceCreatorQuery|null
     */
    public function get92e1aabb9f9642a6B430Edb9f29dbf96()
    {
        return $this->container['_92e1aabb9f9642a6B430Edb9f29dbf96'];
    }

    /**
     * Sets _92e1aabb9f9642a6B430Edb9f29dbf96
     *
     * @param \Zitadel\Client\Model\SessionServiceCreatorQuery|null $_92e1aabb9f9642a6B430Edb9f29dbf96 _92e1aabb9f9642a6B430Edb9f29dbf96
     *
     * @return self
     */
    public function set92e1aabb9f9642a6B430Edb9f29dbf96($_92e1aabb9f9642a6B430Edb9f29dbf96)
    {
        if (is_null($_92e1aabb9f9642a6B430Edb9f29dbf96)) {
            throw new \InvalidArgumentException('non-nullable _92e1aabb9f9642a6B430Edb9f29dbf96 cannot be null');
        }
        $this->container['_92e1aabb9f9642a6B430Edb9f29dbf96'] = $_92e1aabb9f9642a6B430Edb9f29dbf96;

        return $this;
    }

    /**
     * Gets _083493f65d72451383fb9d5f178945a7
     *
     * @return \Zitadel\Client\Model\SessionServiceIDsQuery|null
     */
    public function get083493f65d72451383fb9d5f178945a7()
    {
        return $this->container['_083493f65d72451383fb9d5f178945a7'];
    }

    /**
     * Sets _083493f65d72451383fb9d5f178945a7
     *
     * @param \Zitadel\Client\Model\SessionServiceIDsQuery|null $_083493f65d72451383fb9d5f178945a7 _083493f65d72451383fb9d5f178945a7
     *
     * @return self
     */
    public function set083493f65d72451383fb9d5f178945a7($_083493f65d72451383fb9d5f178945a7)
    {
        if (is_null($_083493f65d72451383fb9d5f178945a7)) {
            throw new \InvalidArgumentException('non-nullable _083493f65d72451383fb9d5f178945a7 cannot be null');
        }
        $this->container['_083493f65d72451383fb9d5f178945a7'] = $_083493f65d72451383fb9d5f178945a7;

        return $this;
    }

    /**
     * Gets _38908444a5bf47a382972b1943eef4db
     *
     * @return object|null
     */
    public function get38908444a5bf47a382972b1943eef4db()
    {
        return $this->container['_38908444a5bf47a382972b1943eef4db'];
    }

    /**
     * Sets _38908444a5bf47a382972b1943eef4db
     *
     * @param object|null $_38908444a5bf47a382972b1943eef4db _38908444a5bf47a382972b1943eef4db
     *
     * @return self
     */
    public function set38908444a5bf47a382972b1943eef4db($_38908444a5bf47a382972b1943eef4db)
    {
        if (is_null($_38908444a5bf47a382972b1943eef4db)) {
            throw new \InvalidArgumentException('non-nullable _38908444a5bf47a382972b1943eef4db cannot be null');
        }
        $this->container['_38908444a5bf47a382972b1943eef4db'] = $_38908444a5bf47a382972b1943eef4db;

        return $this;
    }

    /**
     * Gets b2b79f3503fb473aBaf9E458501ff7cd
     *
     * @return \Zitadel\Client\Model\SessionServiceSendCode|null
     */
    public function getB2b79f3503fb473aBaf9E458501ff7cd()
    {
        return $this->container['b2b79f3503fb473aBaf9E458501ff7cd'];
    }

    /**
     * Sets b2b79f3503fb473aBaf9E458501ff7cd
     *
     * @param \Zitadel\Client\Model\SessionServiceSendCode|null $b2b79f3503fb473aBaf9E458501ff7cd b2b79f3503fb473aBaf9E458501ff7cd
     *
     * @return self
     */
    public function setB2b79f3503fb473aBaf9E458501ff7cd($b2b79f3503fb473aBaf9E458501ff7cd)
    {
        if (is_null($b2b79f3503fb473aBaf9E458501ff7cd)) {
            throw new \InvalidArgumentException('non-nullable b2b79f3503fb473aBaf9E458501ff7cd cannot be null');
        }
        $this->container['b2b79f3503fb473aBaf9E458501ff7cd'] = $b2b79f3503fb473aBaf9E458501ff7cd;

        return $this;
    }

    /**
     * Gets _525266101d1d4f478dfc33cd53a38165
     *
     * @return \Zitadel\Client\Model\SessionServiceUserAgentQuery|null
     */
    public function get525266101d1d4f478dfc33cd53a38165()
    {
        return $this->container['_525266101d1d4f478dfc33cd53a38165'];
    }

    /**
     * Sets _525266101d1d4f478dfc33cd53a38165
     *
     * @param \Zitadel\Client\Model\SessionServiceUserAgentQuery|null $_525266101d1d4f478dfc33cd53a38165 _525266101d1d4f478dfc33cd53a38165
     *
     * @return self
     */
    public function set525266101d1d4f478dfc33cd53a38165($_525266101d1d4f478dfc33cd53a38165)
    {
        if (is_null($_525266101d1d4f478dfc33cd53a38165)) {
            throw new \InvalidArgumentException('non-nullable _525266101d1d4f478dfc33cd53a38165 cannot be null');
        }
        $this->container['_525266101d1d4f478dfc33cd53a38165'] = $_525266101d1d4f478dfc33cd53a38165;

        return $this;
    }

    /**
     * Gets _35b955a40ab54075864d72eadf73bb86
     *
     * @return \Zitadel\Client\Model\SessionServiceUserIDQuery|null
     */
    public function get35b955a40ab54075864d72eadf73bb86()
    {
        return $this->container['_35b955a40ab54075864d72eadf73bb86'];
    }

    /**
     * Sets _35b955a40ab54075864d72eadf73bb86
     *
     * @param \Zitadel\Client\Model\SessionServiceUserIDQuery|null $_35b955a40ab54075864d72eadf73bb86 _35b955a40ab54075864d72eadf73bb86
     *
     * @return self
     */
    public function set35b955a40ab54075864d72eadf73bb86($_35b955a40ab54075864d72eadf73bb86)
    {
        if (is_null($_35b955a40ab54075864d72eadf73bb86)) {
            throw new \InvalidArgumentException('non-nullable _35b955a40ab54075864d72eadf73bb86 cannot be null');
        }
        $this->container['_35b955a40ab54075864d72eadf73bb86'] = $_35b955a40ab54075864d72eadf73bb86;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


