<?php
/**
 * V2SecondFactorType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * merged spec
 *
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;
use \Zitadel\Client\ObjectSerializer;

/**
 * V2SecondFactorType Class Doc Comment
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V2SecondFactorType
{
    /**
     * Possible values of this enum
     */
    public const SECOND_FACTOR_TYPE_UNSPECIFIED = 'SECOND_FACTOR_TYPE_UNSPECIFIED';

    public const SECOND_FACTOR_TYPE_OTP = 'SECOND_FACTOR_TYPE_OTP';

    public const SECOND_FACTOR_TYPE_U2_F = 'SECOND_FACTOR_TYPE_U2F';

    public const SECOND_FACTOR_TYPE_OTP_EMAIL = 'SECOND_FACTOR_TYPE_OTP_EMAIL';

    public const SECOND_FACTOR_TYPE_OTP_SMS = 'SECOND_FACTOR_TYPE_OTP_SMS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SECOND_FACTOR_TYPE_UNSPECIFIED,
            self::SECOND_FACTOR_TYPE_OTP,
            self::SECOND_FACTOR_TYPE_U2_F,
            self::SECOND_FACTOR_TYPE_OTP_EMAIL,
            self::SECOND_FACTOR_TYPE_OTP_SMS
        ];
    }
}


