<?php
/**
 * WebKeyServiceBetaState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zitadel SDK
 *
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;
use \Zitadel\Client\ObjectSerializer;

/**
 * WebKeyServiceBetaState Class Doc Comment
 *
 * @category Class
 * @description - STATE_INITIAL: A newly created key is in the initial state and published to the public key endpoint.  - STATE_ACTIVE: The active key is used to sign tokens. Only one key can be active at a time.  - STATE_INACTIVE: The inactive key is not used to sign tokens anymore, but still published to the public key endpoint.  - STATE_REMOVED: The removed key is not used to sign tokens anymore and not published to the public key endpoint.
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebKeyServiceBetaState
{
    /**
     * Possible values of this enum
     */
    public const STATE_UNSPECIFIED = 'STATE_UNSPECIFIED';

    public const STATE_INITIAL = 'STATE_INITIAL';

    public const STATE_ACTIVE = 'STATE_ACTIVE';

    public const STATE_INACTIVE = 'STATE_INACTIVE';

    public const STATE_REMOVED = 'STATE_REMOVED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STATE_UNSPECIFIED,
            self::STATE_INITIAL,
            self::STATE_ACTIVE,
            self::STATE_INACTIVE,
            self::STATE_REMOVED
        ];
    }
}


