<?php
/**
 * WebKeyServiceBetaRSABits
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zitadel SDK
 *
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zitadel\Client\Model;
use \Zitadel\Client\ObjectSerializer;

/**
 * WebKeyServiceBetaRSABits Class Doc Comment
 *
 * @category Class
 * @package  Zitadel\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebKeyServiceBetaRSABits
{
    /**
     * Possible values of this enum
     */
    public const RSA_BITS_UNSPECIFIED = 'RSA_BITS_UNSPECIFIED';

    public const RSA_BITS_2048 = 'RSA_BITS_2048';

    public const RSA_BITS_3072 = 'RSA_BITS_3072';

    public const RSA_BITS_4096 = 'RSA_BITS_4096';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RSA_BITS_UNSPECIFIED,
            self::RSA_BITS_2048,
            self::RSA_BITS_3072,
            self::RSA_BITS_4096
        ];
    }
}


