<?php

/**
 * Zitadel SDK
 * The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

declare(strict_types=1);

namespace Zitadel\Client;

/**
 * ApiClient Interface
 *
 * @category Interface
 * @package  Zitadel\Client
 */
interface ApiClient
{
    /**
     * Send an HTTP request and return the response.
     *
     * @param string                $method     HTTP method (GET, POST, PUT, DELETE, etc.)
     * @param string                $url        Fully qualified URL
     * @param array<string, string> $headers    HTTP headers
     * @param mixed                 $body       Request body
     * @param bool                  $noRedirect when true, do not follow 3xx responses
     *                                          regardless of {@see TransportOptions::followRedirects}.
     *                                          Set by callers (e.g. {@see OAuth2TokenManager})
     *                                          that must refuse redirect-driven request replays.
     */
    public function sendRequest(
        string $method,
        string $url,
        array $headers,
        mixed $body,
        bool $noRedirect = false,
    ): ApiHttpResponse;
}
