name: Autofix

on:
  workflow_call:
    inputs:
      ref:
        description: 'The Git ref (branch, tag, or SHA) to checkout'
        required: true
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  rector-check:
    runs-on: ubuntu-latest
    name: Run Rector Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Rector
        run: composer rector -- --dry-run --ansi

      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "❌ Rector found pending changes! Please run 'composer rector' locally and commit the fixes."
            exit 1
          fi
