name: Autofix

on:
  workflow_call:
    inputs:
      ref:
        description: 'The Git ref (branch, tag, or SHA) to checkout'
        required: true
        type: string

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  rector-check:
    runs-on: ubuntu-latest
    name: Run Rector Checks

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@27853eb8b46dc01c33bf9fef67d98df2683c3be2 # v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Rector
        run: composer rector -- --dry-run --ansi

      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "❌ Rector found pending changes! Please run 'composer rector' locally and commit the fixes."
            exit 1
          fi
