name: Compatibility

on:
  workflow_call:
    inputs:
      library_ref:
        required: true
        type: string
      sanity_ref:
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-compatibility:
    name: With PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.3', '8.4', '8.5' ]
      fail-fast: false

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.library_ref }}
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.sanity_ref }}
          path: project/sanity

      - name: Set up PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Check Installability
        working-directory: project/sanity
        run: composer require zitadel/client
