name: Compatibility

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-compatibility:
    name: With PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4' ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: project/library

      - name: Checkout sanity stub
        uses: actions/checkout@v4
        with:
          ref: sanity
          path: project/sanity

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Check Installability
        working-directory: project/sanity
        run: composer require zitadel/client
