name: Linting

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

defaults:
  run:
    working-directory: ./

jobs:
  lint-format:
    runs-on: ubuntu-latest
    name: Reformat Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Formatter
        run: composer format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: Apply automated code formatting [skip ci]'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
