name: Linting

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      commit_changes:
        required: false
        type: boolean
        default: false
    permissions:
      contents: write

defaults:
  run:
    working-directory: ./

jobs:
  lint-format:
    runs-on: ubuntu-latest
    name: Reformat Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Formatter
        run: composer format

      - name: Commit Changes
        if: ${{ inputs.commit_changes == true }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: Apply automated code formatting [skip ci]'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
