name: Qodana

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      test_artifact_name:
        required: false
        type: string
        default: test-results
      coverage_artifact_name:
        required: false
        type: string
        default: coverage-report
    secrets:
      QODANA_TOKEN:
        required: true

defaults:
  run:
    working-directory: ./

jobs:
  qodana-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Download Test Reports Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.test_artifact_name }}
          path: ./qodana-downloaded-reports/test-results

      - name: Download Coverage Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ./.qodana/code-coverage

      - name: List Downloaded Coverage Reports
        run: ls -R ./.qodana/code-coverage
        shell: bash

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
