name: Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

defaults:
    run:
        working-directory: ./

jobs:
    publish-package:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2

            -   name: Install Semantic Release
                run: |
                    npm install --global semantic-release $(jq -r '.plugins[] | if type == "string" then . else .[0] end' .releaserc.json)

            -   name: Run semantic-release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
                run: npx semantic-release
