name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      upload_name:
        required: false
        type: string
        default: test-results
      report_name:
        required: false
        type: string
        default: Tests
    permissions:
      contents: read
      actions: read
      checks: write
    secrets:
      BASE_URL:
        required: false
      AUTH_TOKEN:
        required: false
      JWT_KEY:
        required: false
      CLIENT_ID:
        required: false
      CLIENT_SECRET:
        required: false

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Tests
        run: vendor/bin/phpunit
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.upload_name }}
          path: build/reports/**/*.xml

      - name: Generate Report
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: dorny/test-reporter@v2.0.0
        with:
          name: ${{ inputs.report_name }}
          reporter: java-junit
          path: build/reports/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
